export const toolCategoryOrder = ["Store Analysis", "Design & Visual", "UX & Conversion", "Responsive", "Product & Commerce", "Content & AI", "SEO", "Performance", "Accessibility", "Visual & Reference", "Design Workspaces", "Developer", "Testing & Validation", "Release"] as const;
export type ToolCategory = (typeof toolCategoryOrder)[number];
export type ToolSource = "Connected store" | "Public URL" | "Specific page URL" | "Screenshots" | "Saved draft" | "Theme files" | "Selected page" | "Selected text" | "Reference design" | "Analysis result";
export type ToolKind = "analysis" | "generator" | "workspace" | "validation" | "release";
export type ToolDefinition = { id: string; name: string; category: ToolCategory; kind: ToolKind; description: string; outcome: string; analysisFocus: string[]; resultMetrics: string[]; nextActions: string[]; sources: ToolSource[]; connections: string[]; requiresConnection: boolean };

const publicStore: ToolSource[] = ["Public URL", "Connected store"];
const pageEvidence: ToolSource[] = ["Specific page URL", "Screenshots", "Connected store"];
const visualEvidence: ToolSource[] = ["Public URL", "Specific page URL", "Screenshots", "Saved draft"];
const metrics: Record<ToolCategory, string[]> = {
  "Store Analysis": ["Store Health", "Critical Issues", "Warnings", "Passed Checks"], "Design & Visual": ["Design Score", "Evidence", "Recommendations"], "UX & Conversion": ["UX Score", "Friction Points", "Priority Opportunities"], Responsive: ["Mobile Health", "Affected Viewports", "Priority Fixes"], "Product & Commerce": ["Page Health", "Affected Elements", "Purchase Issues"], "Content & AI": ["Proposal Quality", "Evidence Confidence", "Recommended Changes"], SEO: ["SEO Score", "Issues", "Passed Checks"], Performance: ["Performance Indicators", "Affected Assets", "Expected Impact"], Accessibility: ["Accessibility Score", "Issues", "Remediation Priority"], "Visual & Reference": ["Visual Score", "Recognized Patterns", "Recommendations"], "Design Workspaces": ["Draft Health", "Changed Elements", "Version Status"], Developer: ["Implementation Context", "Priority", "Acceptance Criteria"], "Testing & Validation": ["Passed Checks", "Regressions", "Comparison Result"], Release: ["Readiness", "Blockers", "Permission Status"],
};
const defaultActions: Record<ToolKind, string[]> = { analysis: ["Ask AI", "Review findings", "Export report"], generator: ["Create proposal", "Edit manually", "Save version", "Export package"], workspace: ["Edit draft", "Ask AI", "Save version", "Validate"], validation: ["Review checks", "Create issue", "Export report"], release: ["Review release", "Resolve blockers", "Export record"] };
const tool = (id: string, name: string, category: ToolCategory, kind: ToolKind, description: string, focus: string, sources: ToolSource[], outcome?: string, nextActions?: string[], requiresConnection = false, connections: string[] = []): ToolDefinition => ({ id, name, category, kind, description, outcome: outcome ?? `${name} results with scoped evidence, findings, and clear next actions.`, analysisFocus: focus.split(" | "), resultMetrics: metrics[category], nextActions: nextActions ?? defaultActions[kind], sources, connections, requiresConnection });

export const toolCatalog: ToolDefinition[] = [
  tool("storefront-analyzer", "Storefront Analyzer", "Store Analysis", "analysis", "Give the user an overall assessment of a storefront.", "Visual design | Layout | Navigation | Content structure | Product presentation | CTA placement | Mobile responsiveness | Accessibility indicators | SEO indicators | Trust elements | Conversion structure", ["Connected store", "Public URL", "Specific page URL", "Screenshots"], "Overall Store Health with Design, UX, Mobile, Accessibility, SEO, Conversion, performance, critical issues, warnings, and passed checks.", ["Ask AI", "Fix with AI", "Analyze individual issue", "Create redesign", "Open relevant editor", "Export report"]),
  tool("page-analyzer", "Page Analyzer", "Store Analysis", "analysis", "Analyze one selected storefront page.", "Homepage | Product page | Collection/category | Cart | About | Contact | Landing pages | Blog | Custom pages", pageEvidence, "Page Health with structure, hierarchy, UX, content, responsiveness, accessibility, SEO, conversion issues, and exact affected elements."),
  tool("site-structure-analyzer", "Site Structure Analyzer", "Store Analysis", "analysis", "Analyze website architecture and discoverability.", "Navigation | Page hierarchy | Internal links | Main pages | Category structure | Product discovery | Footer navigation | Breadcrumbs | Broken paths", publicStore, "A site structure tree with missing pages, poor hierarchy, deep navigation, confusing paths, orphaned pages, and duplicates.", ["Explore structure", "Ask AI", "Open Layout Composer", "Export report"]),

  tool("visual-design-analyzer", "Visual Design Analyzer", "Design & Visual", "analysis", "Evaluate the visual quality of a storefront.", "Color consistency | Typography | Spacing | Alignment | Visual hierarchy | Composition | Image quality | Button styling | Card consistency | Section consistency | White space", visualEvidence, "Visual Design Score with Critical, Warning, Suggestion, Passed, evidence, recommendation, and fix option.", ["Ask AI", "Fix with AI", "Open Visual Style Studio", "Export report"]),
  tool("layout-analyzer", "Layout Analyzer", "Design & Visual", "analysis", "Examine the physical layout of a page.", "Section arrangement | Content width | Alignment | Grid structure | Columns | Spacing | Container sizes | Element positioning | Overlaps | Empty space", visualEvidence, "Affected sections with structural recommendations.", ["Ask AI", "Fix with AI", "Open Layout Composer", "Export report"]),
  tool("visual-hierarchy-analyzer", "Visual Hierarchy Analyzer", "Design & Visual", "analysis", "Check whether visitors can understand the page, what to notice, and what to do next.", "Heading prominence | CTA prominence | Image prominence | Section ordering | Contrast | Visual weight", visualEvidence, "A hierarchy map with the primary decision and competing elements.", ["Ask AI", "Fix with AI", "Open Layout Composer", "Export report"]),
  tool("typography-analyzer", "Typography Analyzer", "Design & Visual", "analysis", "Check typography selection, hierarchy, readability, and consistency.", "Font selection | Font pairing | Font size | Line height | Letter spacing | Heading hierarchy | Readability | Consistency", visualEvidence, "Typography findings with recommended changes.", ["Ask AI", "Fix with AI", "Open Visual Style Studio", "Export report"]),
  tool("color-contrast-analyzer", "Color & Contrast Analyzer", "Design & Visual", "analysis", "Check palette consistency and visual accessibility contrast.", "Primary colors | Secondary colors | Accent colors | Text/background combinations | CTA contrast | Consistency | Accessibility contrast", visualEvidence, "Contrast findings and an optional complete alternative palette.", ["Ask AI", "Fix with AI", "Open Visual Style Studio", "Export report"]),

  tool("ux-analyzer", "UX Analyzer", "UX & Conversion", "analysis", "Evaluate the overall storefront user experience.", "Navigation | Clarity | Discoverability | Interaction | Content organization | Forms | Product discovery | Checkout experience", pageEvidence),
  tool("conversion-analyzer", "Conversion Analyzer", "UX & Conversion", "analysis", "Evaluate whether the store encourages meaningful customer action.", "CTA placement | Product presentation | Trust | Social proof | Urgency | Value proposition | Pricing presentation | Purchase path", pageEvidence, undefined, ["Ask AI", "Fix with AI", "Open Layout Composer", "Export report"]),
  tool("cta-analyzer", "CTA Analyzer", "UX & Conversion", "analysis", "Check CTA visibility, wording, placement, contrast, hierarchy, repetition, and mobile access.", "CTA visibility | Wording | Placement | Contrast | Hierarchy | Repetition | Mobile accessibility", visualEvidence, "CTA evidence with alternative CTA strategies.", ["Ask AI", "Fix with AI", "Open Content Editor", "Export report"]),
  tool("trust-credibility-analyzer", "Trust & Credibility Analyzer", "UX & Conversion", "analysis", "Find missing trust signals and recommend useful placements.", "Reviews | Testimonials | Trust badges | Secure payment indicators | Return policy | Contact information | Guarantees | Social proof | Brand credibility", visualEvidence, "Missing trust signals with recommended placements.", ["Ask AI", "Fix with AI", "Open Content Editor", "Export report"]),
  tool("customer-journey-analyzer", "Customer Journey Analyzer", "UX & Conversion", "analysis", "Map customer progress from landing through purchase.", "Landing | Discovery | Product | Cart | Checkout | Purchase", publicStore, "A customer-journey map with friction points.", ["Ask AI", "Analyze individual issue", "Developer handoff", "Export report"]),

  tool("responsive-analyzer", "Responsive Analyzer", "Responsive", "analysis", "Check responsive behavior from desktop through mobile.", "Desktop | Tablet | Mobile | Overflow | Broken layouts | Tiny text | Overlaps | Horizontal scrolling | Image sizing | Spacing | Navigation | CTA | Content clipping", visualEvidence, "Mobile Health with critical, warning, and suggestion findings.", ["Fix with AI", "Open Responsive Studio", "Compare desktop/mobile", "Generate developer fix"]),
  tool("mobile-ux-analyzer", "Mobile UX Analyzer", "Responsive", "analysis", "Evaluate mobile storefront usability.", "Navigation | Search | Product discovery | Buttons | Forms | Scrolling | Product interaction | Checkout journey", pageEvidence, undefined, ["Fix with AI", "Open Responsive Studio", "Export report"]),
  tool("breakpoint-analyzer", "Breakpoint Analyzer", "Responsive", "analysis", "Check layouts between desktop, tablet, mobile, and intermediate widths.", "Desktop | Tablet | Mobile | Intermediate viewport widths", visualEvidence, "Breakpoint behavior with affected ranges and overrides.", ["Fix with AI", "Open Responsive Studio", "Generate developer fix", "Export report"]),

  tool("product-page-analyzer", "Product Page Analyzer", "Product & Commerce", "analysis", "Check the complete product-page decision experience.", "Product image | Product title | Price | Description | Variants | Quantity | Add to cart | Buy now | Reviews | Shipping | Returns | Trust signals", pageEvidence),
  tool("product-presentation-analyzer", "Product Presentation Analyzer", "Product & Commerce", "analysis", "Analyze how products are visually presented.", "Image quality | Gallery | Card structure | Pricing | Badges | Product hierarchy", pageEvidence, undefined, ["Ask AI", "Fix with AI", "Open Visual Style Studio", "Export report"]),
  tool("product-content-analyzer", "Product Content Analyzer", "Product & Commerce", "analysis", "Check product content clarity, completeness, and persuasion.", "Product descriptions | Titles | Benefits | Features | Specifications | Readability | Clarity", ["Connected store", "Specific page URL", "Screenshots", "Selected text"], "Product content findings and AI rewrite directions.", ["Ask AI", "Open Content Editor", "Export report"]),
  tool("navigation-analyzer", "Navigation Analyzer", "Product & Commerce", "analysis", "Check menus, search, breadcrumbs, and navigation clarity.", "Main menu | Dropdowns | Footer navigation | Search | Breadcrumbs", pageEvidence, undefined, ["Ask AI", "Fix with AI", "Open Layout Composer", "Export report"]),
  tool("collection-analyzer", "Collection Analyzer", "Product & Commerce", "analysis", "Check category organization, filters, sorting, discovery, and presentation.", "Category organization | Filters | Sorting | Product discovery | Collection presentation", pageEvidence, undefined, ["Ask AI", "Fix with AI", "Open Layout Composer", "Export report"]),
  tool("cart-analyzer", "Cart Analyzer", "Product & Commerce", "analysis", "Check cart clarity, actions, upsells, and shipping information.", "Cart clarity | Product information | Quantity controls | CTA | Upsells | Shipping information", pageEvidence, undefined, ["Ask AI", "Fix with AI", "Open Layout Composer", "Export report"]),
  tool("checkout-ux-analyzer", "Checkout UX Analyzer", "Product & Commerce", "analysis", "Check the checkout portions available through public flow or permissioned platform access.", "Checkout clarity | Forms | Friction | Trust | Payment visibility | Mobile experience", ["Connected store", "Public URL", "Specific page URL"], "Checkout UX findings within the available privacy boundary.", ["Ask AI", "Developer handoff", "Export report"]),

  tool("content-quality-analyzer", "Content Quality Analyzer", "Content & AI", "analysis", "Check content clarity, grammar, readability, consistency, repetition, and missing information.", "Clarity | Grammar | Readability | Consistency | Repetition | Missing information", ["Public URL", "Specific page URL", "Screenshots", "Selected text"], undefined, ["Ask AI", "Open Content Editor", "Export report"]),
  tool("ai-content-improver", "AI Content Improver", "Content & AI", "generator", "Improve selected text using direct instructions such as shorter, clearer, persuasive, professional, or premium.", "Selected text | Tone | Clarity | Length | Persuasiveness", ["Selected text", "Screenshots", "Saved draft"], "Contextual content proposals to review before applying."),
  tool("product-description-generator", "Product Description Generator", "Content & AI", "generator", "Generate product descriptions, benefits, features, short descriptions, and SEO descriptions.", "Product context | Benefits | Features | SEO description", ["Connected store", "Selected text", "Saved draft"], "Product content variations ready for review."),
  tool("cta-generator", "CTA Generator", "Content & AI", "generator", "Generate conversion-focused CTA variations.", "CTA context | Value proposition | Page goal", ["Selected text", "Specific page URL", "Saved draft"], "CTA variations with conversion rationale."),
  tool("seo-content-generator", "SEO Content Generator", "Content & AI", "generator", "Generate meta titles, meta descriptions, headings, alt text, and structured content recommendations.", "Search intent | Page content | Image context", ["Public URL", "Specific page URL", "Selected text", "Saved draft"], "SEO content proposals ready for review."),
  tool("ai-design-copilot", "AI Design Copilot", "Content & AI", "generator", "Use natural language to redesign, fix, restyle, or create a store direction.", "Current page | Selected element | Analysis results | Project | Previous changes | Reference images", ["Connected store", "Public URL", "Screenshots", "Saved draft", "Reference design", "Analysis result"], "A scoped design proposal or draft that stays reviewable before application.", ["Create proposal", "Compare", "Modify", "Chat with AI", "Edit manually", "Save version", "Publish if supported"]),

  tool("seo-analyzer", "SEO Analyzer", "SEO", "analysis", "Check available page SEO and structural indicators.", "Title | Meta description | Headings | URLs | Canonical | Indexing signals | Image alt text | Internal links | Structured data indicators", ["Connected store", "Public URL", "Specific page URL", "Theme files"], undefined, ["Ask AI", "Open Content Editor", "Developer handoff", "Export report"]),
  tool("meta-generator", "Meta Generator", "SEO", "generator", "Generate meta titles, meta descriptions, and social descriptions.", "Page context | Search intent | Brand tone", ["Public URL", "Specific page URL", "Selected text", "Saved draft"], "Metadata variations with page context."),
  tool("heading-structure-analyzer", "Heading Structure Analyzer", "SEO", "analysis", "Check H1, H2, and H3 hierarchy and identify poor document structure.", "H1 | H2 | H3 | Document hierarchy", ["Public URL", "Specific page URL", "Theme files", "Saved draft"], "Heading hierarchy findings and a corrected outline.", ["Ask AI", "Open Content Editor", "Developer handoff", "Export report"]),
  tool("image-seo-analyzer", "Image SEO Analyzer", "SEO", "analysis", "Check image alt text, filenames, dimensions, quality, and optimization opportunities.", "Alt text | Filenames | Dimensions | Image quality | Optimization opportunities", ["Connected store", "Public URL", "Specific page URL", "Theme files"], undefined, ["Ask AI", "Developer handoff", "Export report"]),

  tool("performance-analyzer", "Performance Analyzer", "Performance", "analysis", "Check page load, measurable Core Web Vitals, assets, images, scripts, CSS, fonts, and requests.", "Page load | Core Web Vitals | Large assets | Images | Scripts | CSS | Fonts | Network requests", ["Connected store", "Public URL", "Specific page URL", "Theme files"], "Performance evidence with causes, impact, and delivery recommendations.", ["Review evidence", "Create AI plan", "Developer handoff", "Export report"]),
  tool("image-optimization-analyzer", "Image Optimization Analyzer", "Performance", "analysis", "Find oversized images, inefficient formats, missing responsive sizes, and image weight.", "Oversized images | Inefficient formats | Responsive sizes | Image weight", ["Connected store", "Public URL", "Specific page URL", "Theme files"], "Image optimization opportunities and developer-ready actions.", ["Optimize", "Replace", "Generate optimized version", "Developer handoff", "Export report"]),
  tool("asset-analyzer", "Asset Analyzer", "Performance", "analysis", "Analyze CSS, JavaScript, images, fonts, videos, and third-party resources.", "CSS | JavaScript | Images | Fonts | Videos | Third-party resources", ["Connected store", "Public URL", "Theme files"], "An asset inventory with unnecessary or heavy resources.", ["Review evidence", "Create AI plan", "Developer handoff", "Export report"]),

  tool("accessibility-analyzer", "Accessibility Analyzer", "Accessibility", "analysis", "Check visible and available accessibility indicators.", "Color contrast | Alt text | Heading hierarchy | Labels | Keyboard indicators | Button names | Form accessibility | Semantic structure", ["Connected store", "Public URL", "Specific page URL", "Screenshots", "Theme files"], undefined, ["Review evidence", "Create AI plan", "Developer handoff", "Export report"]),
  tool("accessibility-fix-assistant", "Accessibility Fix Assistant", "Accessibility", "generator", "Turn detected accessibility problems into clear suggested fixes.", "Detected issue | Accessible labels | Remediation steps", ["Analysis result", "Selected page", "Theme files", "Saved draft"], "Recommended accessible labels and developer-ready fixes.", ["Create fix proposal", "Open Content Editor", "Developer handoff", "Export report"]),

  tool("screenshot-analyzer", "Screenshot Analyzer", "Visual & Reference", "analysis", "Analyze an uploaded screenshot for design structure and visual quality.", "Layout | Sections | Typography | Colors | Spacing | Components | Visual hierarchy", ["Screenshots"], "Design analysis with visual recommendations.", ["Ask AI", "Create redesign", "Open Visual Style Studio", "Export report"]),
  tool("design-reference-analyzer", "Design Reference Analyzer", "Visual & Reference", "analysis", "Extract a usable visual direction from an uploaded design reference.", "Visual style | Colors | Typography | Spacing | Layout patterns | Component style", ["Reference design", "Screenshots"], "Reference design guidance for a similar store direction.", ["Create similar direction", "Ask AI", "Open Visual Style Studio", "Save project"]),
  tool("ai-store-redesign", "AI Store Redesign", "Visual & Reference", "generator", "Generate a redesigned storefront version from a URL, connected store, screenshot, or project.", "URL | Connected store | Screenshot | Existing project", ["Connected store", "Public URL", "Screenshots", "Saved draft"], "Comparable redesign alternatives ready for AI and manual refinement.", ["Compare", "Modify", "Chat with AI", "Edit manually", "Save version", "Publish if supported"]),

  tool("layout-composer", "Layout Composer", "Design Workspaces", "workspace", "Manually arrange sections, containers, columns, grids, alignment, spacing, positioning, and order.", "Sections | Containers | Columns | Flex | Grid | Alignment | Spacing | Positioning | Ordering", ["Saved draft", "Selected page", "Analysis result"], "A saved layout draft with live preview and version history."),
  tool("visual-style-studio", "Visual Style Studio", "Design Workspaces", "workspace", "Manually edit colors, typography, borders, shadows, backgrounds, gradients, and effects.", "Colors | Typography | Borders | Shadows | Backgrounds | Gradients | Effects", ["Saved draft", "Selected page", "Analysis result"], "A saved visual-style draft with live preview and version history."),
  tool("responsive-studio", "Responsive Studio", "Design Workspaces", "workspace", "Manually control devices, breakpoints, visibility, overrides, and mobile-specific layout.", "Desktop | Tablet | Mobile | Breakpoints | Visibility | Responsive overrides | Mobile-specific layout", ["Saved draft", "Selected page", "Analysis result"], "A responsive draft with side-by-side device review."),
  tool("content-editor", "Content Editor", "Design Workspaces", "workspace", "Manually edit text, headings, product descriptions, buttons, navigation, FAQs, and testimonials.", "Text | Headings | Product descriptions | Buttons | Navigation | FAQs | Testimonials", ["Saved draft", "Selected page", "Analysis result"], "A saved content draft with AI-assisted revisions."),
  tool("component-builder", "Component Builder", "Design Workspaces", "workspace", "Create reusable buttons, cards, sections, headers, footers, and product components.", "Buttons | Cards | Sections | Headers | Footers | Product components", ["Saved draft", "Selected page", "Analysis result"], "A reusable component proposal or draft."),

  tool("developer-handoff", "Developer Handoff", "Developer", "analysis", "Convert findings into an implementation-ready delivery package.", "Issue | Location | Evidence | Expected behavior | Current behavior | Recommended fix | Priority", ["Analysis result", "Saved draft", "Theme files", "Screenshots"], "A developer handoff with issue, location, evidence, behavior, fix, and priority.", ["Review evidence", "Create AI plan", "Developer handoff", "Export report"]),
  tool("technical-analyzer", "Technical Analyzer", "Developer", "analysis", "Analyze accessible HTML, CSS, scripts, components, assets, and responsive rules where technically available.", "HTML | CSS | Scripts | Components | Assets | Responsive rules", ["Theme files", "Connected store", "Analysis result"], "Technical structure evidence and a safe remediation plan.", ["Review evidence", "Create AI plan", "Developer handoff", "Export report"], true, ["Theme or code access"]),
  tool("theme-code-analyzer", "Theme/Code Analyzer", "Developer", "analysis", "Analyze relevant theme or code files when platform access is legitimately available.", "Relevant files | Potential conflicts | Styling problems | Layout implementation issues", ["Theme files", "Connected store", "Analysis result"], "Theme and code findings with conflicts and implementation recommendations.", ["Review evidence", "Create AI plan", "Developer handoff", "Export report"], true, ["Theme or code repository"]),

  tool("before-after-comparator", "Before/After Comparator", "Testing & Validation", "validation", "Compare original and current results across score and issue movement.", "Before | After | Score movement | Issue movement", ["Saved draft", "Screenshots", "Analysis result"], "A decision-ready before/after comparison.", ["Compare versions", "Save report", "Open validation"]),
  tool("visual-regression-analyzer", "Visual Regression Analyzer", "Testing & Validation", "validation", "Compare versions and identify unexpected visual changes.", "Visual baseline | Current version | Unexpected changes", ["Saved draft", "Screenshots", "Connected store"], "A visual change report with reviewable differences."),
  tool("responsive-regression-tester", "Responsive Regression Tester", "Testing & Validation", "validation", "Check whether a modification damaged another device or viewport.", "Desktop | Tablet | Mobile | Changed breakpoints", ["Saved draft", "Screenshots", "Connected store"], "A responsive regression report by viewport."),
  tool("accessibility-regression-tester", "Accessibility Regression Tester", "Testing & Validation", "validation", "Recheck accessibility after modifications.", "Contrast | Labels | Headings | Keyboard indicators | Structure", ["Saved draft", "Screenshots", "Connected store", "Theme files"], "An accessibility comparison with remaining issues."),
  tool("seo-regression-tester", "SEO Regression Tester", "Testing & Validation", "validation", "Check whether a redesign introduced SEO problems.", "Titles | Descriptions | Headings | URLs | Internal links | Alt text", ["Saved draft", "Connected store", "Theme files"], "An SEO regression report with affected signals."),

  tool("publish-readiness-checker", "Publish Readiness Checker", "Release", "release", "Check every required condition before a supported release.", "Validation | Responsive checks | Accessibility | SEO | Visual comparison | Unresolved critical issues | Platform permissions", ["Saved draft", "Connected store", "Analysis result"], "A release checklist including validation, permissions, and unresolved risks.", ["Open release review", "Resolve blockers", "Export checklist"], true, ["Supported store connection"]),
  tool("publish-manager", "Publish Manager", "Release", "release", "Move a supported store change through Draft, Validate, Review, Approve, and Publish.", "Draft | Validate | Review | Approve | Publish", ["Saved draft", "Connected store"], "A controlled release plan with explicit confirmation.", ["Create store draft", "Review release", "Publish"], true, ["Supported store connection"]),
  tool("rollback", "Rollback", "Release", "release", "Restore a previous published version when the integration supports it.", "Previous version | Published version | Integration support", ["Connected store", "Saved draft"], "A controlled restore plan with version context.", ["Review previous version", "Restore version", "Export rollback record"], true, ["Supported store connection"]),
];

export const toolCategories: Array<ToolCategory | "All tools"> = ["All tools", ...toolCategoryOrder];
export function filterTools(query: string, category: ToolCategory | "All tools") { const terms = query.trim().toLowerCase().split(/\s+/).filter(Boolean); return toolCatalog.filter(tool => (category === "All tools" || tool.category === category) && terms.every(term => [tool.name, tool.category, tool.kind, tool.description, tool.outcome, ...tool.analysisFocus, ...tool.resultMetrics, ...tool.nextActions, ...tool.sources, ...tool.connections].join(" ").toLowerCase().includes(term))); }
export function getToolDefinition(toolId: string) { return toolCatalog.find(tool => tool.id === toolId) ?? toolCatalog[0]; }
