import { ArrowLeft, ArrowRight, Check, CircleCheck, Clock3, Eye, EyeOff, KeyRound, LockKeyhole, Mail, RefreshCw, ShieldCheck, Sparkles, TriangleAlert } from "lucide-react";
import React, { FormEvent, useState } from "react";
import { useLocation } from "wouter";
import { startSimulatedSession } from "@/lib/authSimulation";
import { getSafeReturnPath, withAuthReturn } from "@/lib/authReturn";
import "./auth.css";

const passwordRules = ["At least 8 characters", "One uppercase letter", "One lowercase letter", "One number", "One special character"];
const emailIsValid = (email: string) => /^\S+@\S+\.\S+$/.test(email);
const passwordIsStrong = (password: string) => password.length >= 8 && /[A-Z]/.test(password) && /[a-z]/.test(password) && /\d/.test(password) && /[^A-Za-z0-9]/.test(password);

function BrandMark() { return <a className="auth-brand" href="/"><span>◇</span><b>FERIX<em>RG</em></b></a>; }
function AuthField({ label, value, onChange, placeholder, type = "text", error, trailing }: { label: string; value: string; onChange: (value: string) => void; placeholder: string; type?: string; error?: string; trailing?: React.ReactNode }) { return <label className={`auth-field ${error ? "has-error" : ""}`}><span>{label}</span><div><input aria-label={label} type={type} value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} />{trailing}</div>{error && <small role="alert">{error}</small>}</label>; }
function AuthShell({ title, copy, children, back }: { title: string; copy: string; children: React.ReactNode; back?: () => void }) { return <main className="auth-page"><section className="auth-art"><BrandMark /><div className="auth-art-content"><span>AI storefront intelligence</span><h2>Know what to improve.<br /><b>Make every change count.</b></h2><p>Analyze, redesign, and validate every storefront decision from one focused workspace.</p><div className="auth-art-metrics"><span><b>91</b> store health</span><span><b>3</b> priority actions</span><span><b>14</b> changes ready</span></div></div><small>FerixRG preview workspace</small></section><section className="auth-form-side"><div className="auth-mobile-brand"><BrandMark /></div><div className="auth-card">{back && <button className="auth-back" onClick={back}><ArrowLeft /> Back</button>}<header><span className="auth-eyebrow">FERIXRG ACCOUNT</span><h1>{title}</h1><p>{copy}</p></header>{children}</div></section></main>; }
function Divider() { return <div className="auth-divider"><i /> <span>OR</span> <i /></div>; }
function GoogleButton({ onClick }: { onClick: () => void }) { return <button className="auth-google" onClick={onClick}><span>G</span> Continue with Google</button>; }
function StatusScreen({ icon, title, copy, primary, secondary }: { icon: React.ReactNode; title: string; copy: string; primary: { label: string; onClick: () => void }; secondary?: { label: string; onClick: () => void } }) { return <AuthShell title={title} copy={copy}><div className="auth-status"><div className="auth-status-icon">{icon}</div><button className="auth-primary" onClick={primary.onClick}>{primary.label}<ArrowRight /></button>{secondary && <button className="auth-text-action" onClick={secondary.onClick}>{secondary.label}</button>}</div></AuthShell>; }

export default function Auth() {
  const [location, setLocation] = useLocation();
  const [email, setEmail] = useState("");
  const [name, setName] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [acceptedTerms, setAcceptedTerms] = useState(false);
  const [remember, setRemember] = useState(true);
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirm, setShowConfirm] = useState(false);
  const [loading, setLoading] = useState(false);
  const [formError, setFormError] = useState("");
  const [emailError, setEmailError] = useState("");
  const [nameError, setNameError] = useState("");
  const [passwordError, setPasswordError] = useState("");
  const [confirmError, setConfirmError] = useState("");
  const [forgotSent, setForgotSent] = useState(false);
  const [resendSeconds, setResendSeconds] = useState(0);
  const [emailUpdated, setEmailUpdated] = useState(false);
  const [verified, setVerified] = useState(false);
  const query = new URLSearchParams(window.location.search);
  const route = location.split("?")[0].replace("/auth/", "") || "login";
  const returnPath = getSafeReturnPath(window.location.search);
  const go = (next: string) => { const [nextRoute, nextQuery = ""] = next.split("?"); const params = Object.fromEntries(new URLSearchParams(nextQuery)); setFormError(""); setEmailError(""); setNameError(""); setPasswordError(""); setConfirmError(""); setLocation(withAuthReturn(nextRoute, returnPath, params)); };
  const beginSession = () => { startSimulatedSession(); setLocation(returnPath); };
  const beginLoading = (next: () => void) => { setLoading(true); window.setTimeout(() => { setLoading(false); next(); }, 700); };
  const socialContinue = () => beginLoading(beginSession);
  const resend = () => { setResendSeconds(45); const timer = window.setInterval(() => setResendSeconds(current => { if (current <= 1) { window.clearInterval(timer); return 0; } return current - 1; }), 1000); };

  const submitLogin = (event: FormEvent) => { event.preventDefault(); setFormError(""); setEmailError(""); setPasswordError(""); if (!emailIsValid(email)) return setEmailError("Please enter a valid email address."); if (!password) return setPasswordError("Enter your password to continue."); if (email.includes("unverified")) return setFormError("Your email address hasn’t been verified yet."); if (email.includes("limited")) return setFormError("Too many sign-in attempts. Please wait a moment and try again."); if (email.includes("network")) return setFormError("We couldn’t connect to the server. Check your internet connection and try again."); if (password === "wrong") return setFormError("Incorrect email or password. Please try again."); beginLoading(beginSession); };
  const submitRegister = (event: FormEvent) => { event.preventDefault(); setNameError(""); setEmailError(""); setPasswordError(""); setConfirmError(""); setFormError(""); if (!name.trim()) return setNameError("Please enter your name."); if (!emailIsValid(email)) return setEmailError("Please enter a valid email address."); if (!passwordIsStrong(password)) return setPasswordError("Your password doesn’t meet the requirements."); if (password !== confirmPassword) return setConfirmError("Passwords don’t match."); if (!acceptedTerms) return setFormError("Please accept the Terms of Service and Privacy Policy to continue."); if (email.includes("used")) return setFormError("This email can’t be used to create a new account. Try signing in or resetting your password."); beginLoading(() => go(`verify-email?email=${encodeURIComponent(email)}`)); };
  const submitForgot = (event: FormEvent) => { event.preventDefault(); setEmailError(""); if (!emailIsValid(email)) return setEmailError("Please enter a valid email address."); beginLoading(() => setForgotSent(true)); };
  const submitReset = (event: FormEvent) => { event.preventDefault(); setPasswordError(""); setConfirmError(""); if (!passwordIsStrong(password)) return setPasswordError("Your password doesn’t meet the requirements."); if (password !== confirmPassword) return setConfirmError("Passwords don’t match."); if (password === "Previous1!") return setPasswordError("Please choose a different password."); beginLoading(() => go("reset-success")); };
  const submitEmailChange = (event: FormEvent) => { event.preventDefault(); setEmailError(""); if (!emailIsValid(email)) return setEmailError("Please enter a valid email address."); beginLoading(() => setEmailUpdated(true)); };

  if (route === "register") return <AuthShell title="Create your account" copy="Start analyzing, improving and redesigning your storefront with powerful e-commerce tools."><form className="auth-form" onSubmit={submitRegister}><AuthField label="Full name" value={name} onChange={setName} placeholder="Enter your full name" error={nameError} /><AuthField label="Email address" value={email} onChange={setEmail} placeholder="Enter your email address" error={emailError} /><AuthField label="Password" value={password} onChange={setPassword} placeholder="Create a password" type={showPassword ? "text" : "password"} error={passwordError} trailing={<button type="button" aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff /> : <Eye />}</button>} /><div className="auth-password-rules">{passwordRules.map((rule, index) => <span className={password && [password.length >= 8, /[A-Z]/.test(password), /[a-z]/.test(password), /\d/.test(password), /[^A-Za-z0-9]/.test(password)][index] ? "met" : ""} key={rule}><Check /> {rule}</span>)}</div><AuthField label="Confirm password" value={confirmPassword} onChange={setConfirmPassword} placeholder="Re-enter your password" type={showConfirm ? "text" : "password"} error={confirmError} trailing={<button type="button" aria-label={showConfirm ? "Hide confirmation password" : "Show confirmation password"} onClick={() => setShowConfirm(!showConfirm)}>{showConfirm ? <EyeOff /> : <Eye />}</button>} /><label className="auth-checkbox"><input type="checkbox" checked={acceptedTerms} onChange={event => setAcceptedTerms(event.target.checked)} /><span>I agree to the <button type="button">Terms of Service</button> and <button type="button">Privacy Policy</button>.</span></label>{formError && <AuthError text={formError} actions={email.includes("used") ? [{ label: "Sign In", onClick: () => go("login") }, { label: "Forgot Password", onClick: () => go("forgot-password") }] : undefined} />}<button className="auth-primary" disabled={loading} type="submit">{loading ? <><RefreshCw className="animate-spin" /> Creating account...</> : <>Create Account <ArrowRight /></>}</button><Divider /><GoogleButton onClick={socialContinue} /><p className="auth-switch">Already have an account? <button type="button" onClick={() => go("login")}>Sign In</button></p></form></AuthShell>;
  if (route === "forgot-password") return forgotSent ? <StatusScreen icon={<Mail />} title="Check your email" copy="If the email address is associated with an account, you’ll receive a password reset link shortly." primary={{ label: "Open Email", onClick: () => undefined }} secondary={{ label: "Back to Sign In", onClick: () => go("login") }} /> : <AuthShell title="Reset your password" copy="Enter the email address associated with your account and we’ll send you instructions to reset your password." back={() => go("login")}><form className="auth-form" onSubmit={submitForgot}><AuthField label="Email address" value={email} onChange={setEmail} placeholder="Enter your email address" error={emailError} /><button className="auth-primary" disabled={loading} type="submit">{loading ? <><RefreshCw className="animate-spin" /> Sending link...</> : <>Send Reset Link <ArrowRight /></>}</button><p className="auth-switch"><button type="button" onClick={() => go("login")}>Back to Sign In</button></p></form></AuthShell>;
  if (route === "reset-password") return <AuthShell title="Create a new password" copy="Choose a strong password for your account." back={() => go("login")}><form className="auth-form" onSubmit={submitReset}><AuthField label="New password" value={password} onChange={setPassword} placeholder="Enter new password" type={showPassword ? "text" : "password"} error={passwordError} trailing={<button type="button" aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff /> : <Eye />}</button>} /><div className="auth-password-rules">{passwordRules.map(rule => <span key={rule}><Check /> {rule}</span>)}</div><AuthField label="Confirm new password" value={confirmPassword} onChange={setConfirmPassword} placeholder="Re-enter new password" type={showConfirm ? "text" : "password"} error={confirmError} trailing={<button type="button" aria-label={showConfirm ? "Hide confirmation password" : "Show confirmation password"} onClick={() => setShowConfirm(!showConfirm)}>{showConfirm ? <EyeOff /> : <Eye />}</button>} /><button className="auth-primary" disabled={loading} type="submit">{loading ? <><RefreshCw className="animate-spin" /> Resetting password...</> : <>Reset Password <ArrowRight /></>}</button></form></AuthShell>;
  if (route === "reset-success") return <StatusScreen icon={<CircleCheck />} title="Password updated" copy="Your password has been changed successfully. You can now sign in with your new password." primary={{ label: "Sign In", onClick: () => go("login") }} />;
  if (route === "reset-expired") return <StatusScreen icon={<Clock3 />} title="Reset link expired" copy="This password reset link is no longer valid. Request a new one to reset your password." primary={{ label: "Request New Reset Link", onClick: () => go("forgot-password") }} secondary={{ label: "Back to Sign In", onClick: () => go("login") }} />;
  if (route === "reset-invalid") return <StatusScreen icon={<TriangleAlert />} title="Invalid reset link" copy="This password reset link is invalid or has already been used." primary={{ label: "Request New Reset Link", onClick: () => go("forgot-password") }} />;
  if (route === "change-email") return <AuthShell title="Update your email" copy="Enter the email address you’d like to use for your account." back={() => go("verify-email")}><form className="auth-form" onSubmit={submitEmailChange}><AuthField label="Email address" value={email} onChange={setEmail} placeholder="Enter your email address" error={emailError} />{emailUpdated && <div className="auth-inline-success"><Check /> Verification email sent to your new address.</div>}<button className="auth-primary" disabled={loading} type="submit">{loading ? <><RefreshCw className="animate-spin" /> Updating...</> : <>Update Email <ArrowRight /></>}</button></form></AuthShell>;
  if (route === "verify-email") { const targetEmail = (query.get("email") ?? email) || "user@example.com"; return verified ? <StatusScreen icon={<CircleCheck />} title="Email verified" copy="Your account has been verified successfully." primary={{ label: "Continue", onClick: () => go("onboarding") }} /> : <AuthShell title="Verify your email" copy={`We’ve sent a verification link to ${targetEmail}. Open the email and click the verification link to activate your account.`}><div className="auth-status"><div className="auth-status-icon waiting"><Mail /></div><div className="auth-waiting"><i /><span>Waiting for verification...</span></div><button className="auth-primary" onClick={() => setVerified(true)}>I’ve verified my email <ArrowRight /></button><button className="auth-secondary" onClick={() => undefined}>Open Email</button><button className="auth-text-action" disabled={resendSeconds > 0} onClick={resend}>{resendSeconds > 0 ? `Resend in 00:${String(resendSeconds).padStart(2, "0")}` : "Resend Verification Email"}</button><button className="auth-text-action" onClick={() => go("change-email")}>Change Email Address</button></div></AuthShell>; }
  if (route === "verification-success") return <StatusScreen icon={<CircleCheck />} title="Email verified" copy="Your account has been verified successfully." primary={{ label: "Continue", onClick: () => go("onboarding") }} />;
  if (route === "verification-expired") return <StatusScreen icon={<Clock3 />} title="Verification link expired" copy="This verification link is no longer valid. Request a new verification email to continue." primary={{ label: "Send New Verification Link", onClick: () => go("verify-email") }} />;
  if (route === "verification-invalid") return <StatusScreen icon={<TriangleAlert />} title="Invalid verification link" copy="This verification link is invalid or has already been used." primary={{ label: "Request New Verification Email", onClick: () => go("verify-email") }} />;
  if (route === "onboarding") return <AuthShell title="Your workspace is ready" copy="A brief orientation before you start improving your storefront."><div className="auth-onboarding"><span><Check /> Store intelligence is ready</span><span><Check /> Your tools are organized by task</span><span><Check /> You can connect a store whenever you need private context</span><button className="auth-primary" onClick={beginSession}>Go to dashboard <ArrowRight /></button><button className="auth-text-action" onClick={beginSession}>Skip for now</button></div></AuthShell>;
  const isSessionExpired = query.get("reason") === "session";
  return <AuthShell title="Welcome back" copy="Sign in to continue managing, analyzing and improving your storefronts."><form className="auth-form" onSubmit={submitLogin}><AuthField label="Email address" value={email} onChange={setEmail} placeholder="Enter your email address" error={emailError} /><AuthField label="Password" value={password} onChange={setPassword} placeholder="Enter your password" type={showPassword ? "text" : "password"} error={passwordError} trailing={<button type="button" aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff /> : <Eye />}</button>} /><div className="auth-options"><label className="auth-checkbox"><input type="checkbox" checked={remember} onChange={event => setRemember(event.target.checked)} /><span>Remember me</span></label><button type="button" onClick={() => go("forgot-password")}>Forgot password?</button></div>{formError && <AuthError text={formError} actions={formError.includes("verified") ? [{ label: "Resend verification email", onClick: () => go("verify-email") }] : undefined} />}<button className="auth-primary" disabled={loading} type="submit">{loading ? <><RefreshCw className="animate-spin" /> Signing in...</> : <>Sign In <ArrowRight /></>}</button><Divider /><GoogleButton onClick={socialContinue} /><p className="auth-switch">Don’t have an account? <button type="button" onClick={() => go("register")}>Create an account</button></p></form>{isSessionExpired && <div className="auth-session-layer" role="dialog" aria-modal="true" aria-labelledby="auth-session-expired-title"><div><ShieldCheck /><h2 id="auth-session-expired-title">Your session has expired</h2><p>For your security, you’ve been signed out. Please sign in again to continue.</p><button className="auth-primary" onClick={() => setLocation("/auth/login")}>Sign In <ArrowRight /></button></div></div>}</AuthShell>;
}

function AuthError({ text, actions }: { text: string; actions?: Array<{ label: string; onClick: () => void }> }) { return <div className="auth-error" role="alert"><TriangleAlert /><div><b>{text}</b>{actions && <span>{actions.map(action => <button type="button" onClick={action.onClick} key={action.label}>{action.label}</button>)}</span>}</div></div>; }
