/* FerixRG — Quiet Instrument Panel: a focused operational workspace where every interaction is tied to evidence and a clear next move. */
import { Activity, ArrowRight, BarChart3, Bell, Bot, Check, ChevronRight, Code2, Eye, FileBarChart, LayoutDashboard, Layers3, Lightbulb, Monitor, MoreHorizontal, PanelRightOpen, Play, Plus, RefreshCw, ScanLine, Search, Settings, ShieldCheck, Sparkles, TabletSmartphone, Wand2 } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation } from "wouter";

const markAsset = "/manus-storage/ferixrg-mark_1f427345.png";
const evidenceAsset = "/manus-storage/ferixrg-analysis-evidence_b61b40c0.png";
const redesignAsset = "/manus-storage/ferixrg-redesign-compare_034828ad.png";

const navItems = [
  { label: "Overview", icon: LayoutDashboard }, { label: "Analysis", icon: ScanLine }, { label: "Issues", icon: ShieldCheck }, { label: "Redesign", icon: Sparkles }, { label: "Visual editor", icon: Layers3 }, { label: "Preview & validate", icon: Monitor }, { label: "Versions", icon: Activity }, { label: "Reports", icon: FileBarChart }, { label: "Developer tools", icon: Code2 },
];
const metrics = [["Design", "88", "+4.2"], ["Responsive", "71", "3 issues"], ["UX", "84", "+2.1"], ["Conversion", "79", "+5.0"], ["Accessibility", "92", "+1.6"], ["Performance", "76", "2 assets"]];
const analyzers = [["Design", "88", "Structure and hierarchy are clear across core pages."], ["Responsive", "71", "Three collisions interrupt the mobile purchase path."], ["UX", "84", "Navigation and decision flow are steady."], ["Conversion", "79", "Trust signals can arrive sooner on product pages."], ["SEO", "86", "Two product pages need a stronger meta description."], ["Accessibility", "92", "One contrast improvement remains."]];
const issues = [
  { severity: "High", title: "Purchase action loses visual hierarchy", detail: "The primary CTA falls below the initial visual scan on mobile after the product gallery. It competes with secondary actions at the decision point.", tag: "Product page", impact: "Conversion", measures: [["Viewport", "390 px"], ["Element", "Buy button"], ["Impact", "High"], ["Status", "Open"]] },
  { severity: "High", title: "Header overlaps product image at 375px", detail: "The sticky header height intrudes on the image transition at smaller mobile widths, reducing visible product context.", tag: "Product page", impact: "Responsive", measures: [["Viewport", "375 px"], ["Element", "Header"], ["Overflow", "18 px"], ["Status", "Open"]] },
  { severity: "Medium", title: "Trust details arrive after the decision point", detail: "Shipping and returns information are separated from the purchase action and are less visible to a first-time visitor.", tag: "Product page", impact: "Conversion", measures: [["Viewport", "All"], ["Element", "Trust row"], ["Priority", "Medium"], ["Status", "Open"]] },
  { severity: "Low", title: "Secondary body text is low-contrast", detail: "Supporting text in the information grid is visually quiet enough to reduce sustained reading comfort.", tag: "Homepage", impact: "Accessibility", measures: [["Contrast", "3.8:1"], ["Element", "Body copy"], ["Required", "4.5:1"], ["Status", "Open"]] },
];

function Brand() { return <a className="brand" href="/"><img src={markAsset} alt="FerixRG" /><span>FERIX<b>RG</b></span></a>; }

export default function Workspace() {
  const [location] = useLocation();
  const initialView = useMemo(() => {
    if (location.includes("issues")) return "Issues"; if (location.includes("redesign")) return "Redesign"; if (location.includes("editor")) return "Visual editor"; if (location.includes("analysis")) return "Analysis"; return "Overview";
  }, [location]);
  const [view, setView] = useState(initialView);
  const [selectedIssue, setSelectedIssue] = useState(issues[0]);
  const [filter, setFilter] = useState("All");
  const [generated, setGenerated] = useState(false);
  const [scanRunning, setScanRunning] = useState(false);

  const changeView = (next: string) => { setView(next); window.scrollTo({ top: 0, behavior: "smooth" }); };
  return <div className="workspace">
    <aside className="app-sidebar"><Brand /><div className="workspace-pill">Store workspace</div><nav className="app-nav">{navItems.slice(0,7).map(item => <button key={item.label} className={view===item.label ? "active" : ""} onClick={() => changeView(item.label)}><item.icon /> {item.label}</button>)}</nav><div className="workspace-pill">Operate</div><nav className="app-nav">{navItems.slice(7).map(item => <button key={item.label} className={view===item.label ? "active" : ""} onClick={() => changeView(item.label)}><item.icon /> {item.label}</button>)}<button><Settings /> Settings</button></nav><div className="store-mini"><div className="store-mini-top"><div className="store-orb">AT</div><div><strong>Atelier Forma</strong><span>Full control · Production</span></div></div><button onClick={() => changeView("Overview")}>Switch store</button></div></aside>
    <main className="app-main"><header className="app-topbar"><div className="top-context"><div className="store-dot" /><div><span className="crumb">Stores / Atelier Forma /</span><strong>{view}</strong></div></div><div className="top-actions"><button className="search-trigger" onClick={() => changeView("Analysis")}><Search size={14}/> Search anything <kbd>⌘ K</kbd></button><button className="round-icon" onClick={() => changeView("Issues")} aria-label="Open notifications"><Bell /></button><button className="app-button" onClick={() => {setScanRunning(true); changeView("Analysis");}}><RefreshCw size={14} className={scanRunning ? "animate-spin" : ""}/><span>{scanRunning ? "Scanning" : "Re-scan"}</span></button></div></header><div className="app-content">{renderView()}</div></main>
    <nav className="mobile-app-nav" aria-label="Mobile workspace navigation">
      <button className={view==="Overview" ? "active" : ""} onClick={() => changeView("Overview")}><LayoutDashboard /><span>Home</span></button>
      <button className={view==="Analysis" ? "active" : ""} onClick={() => changeView("Analysis")}><ScanLine /><span>Analyze</span></button>
      <button className={view==="Issues" ? "active" : ""} onClick={() => changeView("Issues")}><ShieldCheck /><span>Issues</span></button>
      <button className={view==="Redesign" ? "active" : ""} onClick={() => changeView("Redesign")}><Sparkles /><span>Create</span></button>
      <button className={view==="Reports" ? "active" : ""} onClick={() => changeView("Reports")}><MoreHorizontal /><span>More</span></button>
    </nav>
  </div>;

  function PageHeading({ label, title, copy, action }: { label: string; title: string; copy: string; action?: React.ReactNode }) { return <div className="page-heading"><div><span className="eyebrow">{label}</span><h1>{title}</h1><p className="subtle">{copy}</p></div>{action}</div>; }

  function renderView() {
    if (view === "Overview") return <Overview />;
    if (view === "Analysis") return <Analysis />;
    if (view === "Issues") return <Issues />;
    if (view === "Redesign") return <Redesign />;
    if (view === "Visual editor") return <Editor />;
    if (view === "Preview & validate") return <Placeholder title="Validation is ready when a change is." copy="Enter a preview, compare against the original, and run a staged re-scan across the analysis lenses before you save a version." icon={<Monitor />} action="Open a visual preview" />;
    if (view === "Versions") return <Placeholder title="Every deliberate change deserves a trace." copy="Review the draft history, compare score changes, restore a prior version, and keep publish decisions grounded in validation evidence." icon={<Activity />} action="Create a baseline version" />;
    if (view === "Reports") return <Placeholder title="Make the audit easy to act on." copy="Turn the current score, issue evidence, fixes, and before/after outcomes into a structured store report for the wider team." icon={<FileBarChart />} action="Prepare audit report" />;
    return <Placeholder title="A technical answer should include the context." copy="Use the Developer Tools to scan a URL, inspect responsive evidence, and create a concise implementation handoff." icon={<Code2 />} action="Start a URL diagnostic" />;
  }

  function Overview() { return <>
    <PageHeading label="Store intelligence / Last scan 4 min ago" title="A clear read on Atelier Forma." copy="The selected storefront is healthy enough to improve with intent — 7 issues are worth attention." action={<button className="app-button" onClick={() => changeView("Redesign")}><Sparkles /> Start redesign</button>} />
    <div className="overview-grid"><section className="health-card instrument-card"><span className="card-eyebrow">Store health</span><div className="health-card-inner"><div className="small-score-ring"><b>82</b><span>out of 100</span></div><div className="health-copy"><h2>A strong base, with a visible mobile gap.</h2><p>The next improvement is concentrated around the purchase path. A safe responsive adjustment can create the clearest lift.</p></div></div><div className="evidence-ribbon"><span>Focus area <b>Product page at 390px</b></span><span><b>3</b> high-priority issues</span></div></section><section className="next-card instrument-card"><span className="card-eyebrow" style={{color:'#155eef'}}>What should happen next?</span><h2>Decisions, sequenced.</h2><div className="next-actions">{[["01","Inspect mobile evidence","See exactly what loses hierarchy."],["02","Compare a responsive direction","Preserve the current brand character."],["03","Validate before release","Keep a versioned outcome."]].map(([n,t,c],i)=><button className="next-action" key={n} onClick={() => changeView(i===0?"Issues":i===1?"Redesign":"Preview & validate")}><span className="step">{n}</span><span><b>{t}</b><span>{c}</span></span><ChevronRight size={15}/></button>)}</div></section></div>
    <section className="metrics-row">{metrics.map(([name,score,delta], index) => <button className="metric-card" key={name} onClick={() => changeView("Analysis")}><span>{name}</span><b>{score}</b><small className={index===1||index===5?"warn":""}>{delta}</small></button>)}</section>
    <div className="lower-grid"><section className="chart-card instrument-card"><div className="card-header"><div><span className="card-eyebrow" style={{color:'#155eef'}}>Score history</span><h3>Measured improvement, not a mystery.</h3><p>Last six store scans</p></div><button className="text-link" onClick={() => changeView("Reports")}>Open reports</button></div><div className="bar-chart">{[71,74,72,78,76,82].map((h,i)=><div className="bar-col" key={i}><b>{h}</b><div className={i===5?"bar highlight":"bar"} style={{height:`${h}%`}}/><span>Scan {i+1}</span></div>)}</div><div className="chart-legend"><span>Current health</span><strong>+11 points since baseline</strong></div></section><section className="activity-card instrument-card"><div className="card-header"><div><span className="card-eyebrow" style={{color:'#155eef'}}>Activity</span><h3>A shared operational record.</h3></div><button className="text-link" onClick={() => changeView("Versions")}>View all</button></div><div className="activity-feed">{[[<ScanLine/>,"Responsive scan completed","3 high-priority findings surfaced","4 min ago"],[<Sparkles/>,"Redesign direction saved","Premium mobile alternative is ready to compare","22 min ago"],[<Check/>,"Contrast adjustment validated","Homepage body copy now passes target ratio","Yesterday"]].map(([icon,title,copy,time],i)=><div className="activity-item" key={i}><span className="activity-icon">{icon}</span><span><b>{title}</b><p>{copy}</p></span><time>{time}</time></div>)}</div></section></div>
  </> }

  function Analysis() { const stages = [["Website reachable",true],["Page discovery",true],["Mobile render",true],["Technical inspection",scanRunning?false:true],["Issue consolidation",false]]; return <>
    <PageHeading label="Analyze / Atelier Forma" title="The evidence is getting specific." copy="Choose a lens to understand its score, evidence, and available next actions." action={<button className="app-button" onClick={() => setScanRunning(!scanRunning)}>{scanRunning ? <><RefreshCw className="animate-spin"/> Run in progress</> : <><Play/> Run focused scan</>}</button>} />
    <div className="analysis-layout"><aside className="scan-panel instrument-card"><span className="card-eyebrow" style={{color:'#155eef'}}>Analysis run #18</span><h3>{scanRunning ? "Inspecting the product page" : "Most recent store scan"}</h3><p>{scanRunning ? "The workspace will update evidence as each stage completes." : "Homepage, product page, collection, cart, desktop, tablet, and mobile."}</p>{stages.map(([label,state], i) => <div className={`scan-stage ${state ? "complete" : i===3&&scanRunning ? "active" : ""}`} key={String(label)}><i className="scan-dot" /> {label}</div>)}<div className="scan-footer"><span>{scanRunning ? "62% complete" : "Completed 4 min ago"}</span><span>{scanRunning ? "Working" : "7 open issues"}</span></div></aside><div className="analysis-main"><section className="analyzer-feature"><div className="analysis-summary"><div><span className="card-eyebrow">Current signal</span><h2>Responsive behavior needs the next decision.</h2><p>Three mobile conditions interrupt the product path. The evidence is limited to the relevant viewport and page—not an abstract warning.</p></div><div className="tiny-stats"><span><b>390px</b><span>viewport</span></span><span><b>3</b><span>priority issues</span></span></div></div></section><section className="analyzer-grid">{analyzers.map(([name,score,copy])=><button className="analyzer-card" onClick={() => changeView(name === "Responsive" ? "Issues" : "Redesign")} key={name}><span className="analyzer-top"><span>{name}</span><ChevronRight size={13}/></span><b className={name==="Responsive"?"analyzer-score caution":"analyzer-score"}>{score}</b><p>{copy}</p></button>)}</section></div></div>
  </> }

  function Issues() { const filtered = filter === "All" ? issues : issues.filter(issue => issue.severity === filter); return <>
    <PageHeading label="Issue center / 7 open" title="Every finding has a path forward." copy="Filter the evidence by severity, then open the issue to choose a safe fix, a redesign route, or a developer handoff." action={<button className="app-button" onClick={() => changeView("Redesign")}><Wand2 /> Create a responsive direction</button>} />
    <div className="issues-layout"><section className="issue-board instrument-card"><div className="issue-filterbar"><div className="filter-chips">{["All","High","Medium","Low"].map(f=><button className={filter===f?"filter-chip active":"filter-chip"} onClick={() => setFilter(f)} key={f}>{f}{f==="All"?" issues":""}</button>)}</div><button className="text-link" onClick={() => setFilter("All")}>Clear filters</button></div>{filtered.map(issue => <button className="issue-row" onClick={() => setSelectedIssue(issue)} key={issue.title}><span className={`severity ${issue.severity.toLowerCase()}`}>{issue.severity}</span><span><b>{issue.title}</b><p>{issue.detail.slice(0, 78)}…</p></span><span className="tag">{issue.tag}</span><span className="impact">{issue.impact}</span><ChevronRight /></button>)}</section><aside className="issue-detail instrument-card"><span className={`severity ${selectedIssue.severity.toLowerCase()}`}>{selectedIssue.severity} priority</span><h2>{selectedIssue.title}</h2><p>{selectedIssue.detail}</p><div className="issue-evidence"><img src={evidenceAsset} alt="Selected issue evidence" /></div><div className="measure-grid">{selectedIssue.measures.map(([label,value]) => <div className="measure" key={label}><span>{label}</span><b>{value}</b></div>)}</div><button className="app-button" onClick={() => changeView("Redesign")}><Sparkles /> Generate solution</button><button className="app-button ghost" style={{width:'100%',justifyContent:'center',marginTop:8}} onClick={() => changeView("Visual editor")}><Layers3 /> Open in editor</button></aside></div>
  </> }

  function Redesign() { return <>
    <PageHeading label="AI redesign / Product page" title="Preserve what works. Recompose what doesn’t." copy="The proposal remains linked to the current responsive evidence and is ready to compare before it becomes a version." action={<button className="app-button" onClick={() => setGenerated(true)}><Sparkles /> {generated ? "Direction created" : "Generate direction"}</button>} />
    <div className="redesign-layout-app"><aside className="brief-card instrument-card"><span className="card-eyebrow" style={{color:'#155eef'}}>Redesign brief</span><h3>What must remain true?</h3>{[["Keep product photography",true],["Preserve brand palette",true],["Prioritize 390px purchase path",true],["Make a bolder hierarchy",false],["Use a premium direction",false]].map(([label,active])=><button className={active?"brief-option active":"brief-option"} key={String(label)}><span>{label}</span>{active?<Check/>:<Plus/>}</button>)}<button className="app-button" onClick={() => setGenerated(true)}><Wand2 /> Generate alternatives</button></aside><section className="redesign-main"><div className="generation-status"><span><b>{generated ? "New alternative is ready to review." : "Two evidence-based alternatives are ready."}</b><p>{generated ? "Generated from mobile purchase-path evidence." : "Both preserve the product narrative and current brand palette."}</p></span><span className="live"><i /> proposal mode</span></div><div className="alternatives">{[["A","Premium purchase path","More breathing room around the decision point."],["B","Conversion-led hierarchy","Trust details arrive at the moment of intent."],["C","Mobile clarity pass","A reserved third direction, generated from your brief."]].slice(0,generated?3:2).map(([tag,title,copy],i)=><div className="alternative-card" key={tag}><div className="preview"><img src={redesignAsset} alt={`${title} redesign alternative`} /><span className="score-gain">+{i===1?"14":"11"} projected points</span></div><h3>{tag} / {title}</h3><p>{copy}</p><div className="alternative-actions"><button onClick={() => changeView("Preview & validate")}>Compare</button><button onClick={() => changeView("Visual editor")}>Open in editor</button></div></div>)}</div></section></div>
  </> }

  function Editor() { const [device,setDevice] = useState("Mobile"); return <><PageHeading label="Visual editor / Draft v3" title="Refine the selected decision." copy="Every property change is contained in the draft and can be validated against the original storefront." action={<button className="app-button" onClick={() => changeView("Preview & validate")}><Eye /> Preview changes</button>} /><section className="editor-shell"><aside className="editor-pane"><span className="card-eyebrow" style={{color:'#155eef'}}>Layers</span><h3>Product page</h3>{["Header","Product media","Product content","Heading","Price & purchase","Trust row","Description"].map((layer,i)=><button className={`layer-item ${i===4?"active":""} ${i>2?"layer-indent":""}`} key={layer}><i className="layer-node" /> {layer}</button>)}</aside><div className="editor-canvas"><div className="viewport-toolbar">{["Desktop","Tablet","Mobile"].map(item=><button className={device===item?"active":""} onClick={() => setDevice(item)} key={item}>{item}</button>)}</div><div className="store-preview"><img src={evidenceAsset} alt="Editable storefront canvas"/><div className="selection-box"><span>Purchase action</span><i /><i /></div></div></div><aside className="editor-pane right"><span className="card-eyebrow" style={{color:'#155eef'}}>Properties</span><h3>Purchase action</h3><div className="prop-group"><span>Spacing</span><div className="prop-controls"><div className="prop-control">Top<b>24 px</b></div><div className="prop-control">Bottom<b>16 px</b></div></div></div><div className="prop-group"><span>Typography</span><div className="prop-controls"><div className="prop-control">Weight<b>700</b></div><div className="prop-control">Size<b>16 px</b></div></div></div><div className="prop-group"><span>Appearance</span><div className="prop-control">Accent color<div className="color-swatch"/></div></div><button className="app-button" onClick={() => changeView("Preview & validate")}><Check /> Save draft</button></aside></section></> }

  function Placeholder({ title, copy, icon, action }: { title: string; copy: string; icon: React.ReactNode; action: string }) { return <><PageHeading label="Store operations / Atelier Forma" title={title} copy={copy} /><section className="placeholder-page"><div><div className="empty-icon">{icon}</div><h2>{title}</h2><p>{copy}</p><button className="app-button" onClick={() => changeView("Analysis")}><ArrowRight /> {action}</button></div></section></> }
}
