import { ArrowLeft, ArrowRight, Check, CircleCheck, Clock3, Eye, EyeOff, KeyRound, LockKeyhole, Mail, RefreshCw, ShieldCheck, Sparkles, TriangleAlert } from "lucide-react";
import React, { FormEvent, useEffect, useRef, useState } from "react";
import { useLocation } from "wouter";
import { getSafeReturnPath, withAuthReturn } from "@/lib/authReturn";
import { trpc } from "@/lib/trpc";
import { LocalAccountApiError, confirmAccountEmailChange, loginLocalAccount, registerLocalAccount, requestPasswordReset, resendVerificationEmail, resetLocalPassword, verifyLocalAccount, verifyTwoStepLocalAccount } from "@/lib/localAccountApi";
import "./auth.css";

const passwordRules = ["At least 8 characters", "One uppercase letter", "One lowercase letter", "One number", "One special character"];
const emailIsValid = (email: string) => /^\S+@\S+\.\S+$/.test(email);
const passwordIsStrong = (password: string) => password.length >= 8 && /[A-Z]/.test(password) && /[a-z]/.test(password) && /\d/.test(password) && /[^A-Za-z0-9]/.test(password);
const openMailApp = (address?: string) => { window.location.href = address?.trim() ? `mailto:${encodeURIComponent(address.trim())}` : "mailto:"; };

function BrandMark() { return <a className="auth-brand" href="/"><span>◇</span><b>FERIX<em>RG</em></b></a>; }
function AuthField({ label, value, onChange, placeholder, type = "text", error, trailing }: { label: string; value: string; onChange: (value: string) => void; placeholder: string; type?: string; error?: string; trailing?: React.ReactNode }) { return <label className={`auth-field ${error ? "has-error" : ""}`}><span>{label}</span><div><input aria-label={label} type={type} value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} />{trailing}</div>{error && <small role="alert">{error}</small>}</label>; }
function AuthShell({ title, copy, children, back }: { title: string; copy: string; children: React.ReactNode; back?: () => void }) { return <main className="auth-page"><section className="auth-art"><BrandMark /><div className="auth-art-content"><span>AI storefront intelligence</span><h2>Know what to improve.<br /><b>Make every change count.</b></h2><p>Analyze, redesign, and validate every storefront decision from one focused workspace.</p><div className="auth-art-metrics"><span><b>Secure</b> account access</span><span><b>Scoped</b> workspace data</span><span><b>Clear</b> next steps</span></div></div><small>FerixRG account access</small></section><section className="auth-form-side"><div className="auth-mobile-brand"><BrandMark /></div><div className="auth-card">{back && <button className="auth-back" onClick={back}><ArrowLeft /> Back</button>}<header><span className="auth-eyebrow">FERIXRG ACCOUNT</span><h1>{title}</h1><p>{copy}</p></header>{children}</div></section></main>; }
function Divider() { return <div className="auth-divider"><i /> <span>OR</span> <i /></div>; }
function GoogleButton({ onClick }: { onClick: () => void }) { return <button className="auth-google" onClick={onClick}><span>G</span> Continue with Google</button>; }
function StatusScreen({ icon, title, copy, primary, secondary }: { icon: React.ReactNode; title: string; copy: string; primary: { label: string; onClick: () => void }; secondary?: { label: string; onClick: () => void } }) { return <AuthShell title={title} copy={copy}><div className="auth-status"><div className="auth-status-icon">{icon}</div><button className="auth-primary" onClick={primary.onClick}>{primary.label}<ArrowRight /></button>{secondary && <button className="auth-text-action" onClick={secondary.onClick}>{secondary.label}</button>}</div></AuthShell>; }

function EmailChangeScreen({ initialEmail, back }: { initialEmail: string; back: () => void }) {
  const [email, setEmail] = useState(initialEmail);
  const [emailError, setEmailError] = useState("");
  const [formError, setFormError] = useState("");
  const [emailUpdated, setEmailUpdated] = useState(false);
  const [loading, setLoading] = useState(false);
  const requestEmailChangeMutation = trpc.account.requestEmailChange.useMutation();
  const submit = async (event: FormEvent) => {
    event.preventDefault();
    setEmailError(""); setFormError("");
    if (!emailIsValid(email)) return setEmailError("Please enter a valid email address.");
    setLoading(true);
    try {
      const result = await requestEmailChangeMutation.mutateAsync({ email: email.trim() });
      setEmailUpdated(result.delivery !== "not_needed");
      setFormError(result.delivery === "sent" ? "A confirmation email was sent to your new address." : result.delivery === "not_configured" ? "Email delivery is not configured in this environment yet. No confirmation email was sent." : result.delivery === "failed" ? "The confirmation email could not be delivered. No email change was completed." : "That address is already your current account email.");
    } catch (error) {
      setFormError(error instanceof Error ? error.message : "We couldn’t request an email change. Please try again.");
    } finally { setLoading(false); }
  };
  return <AuthShell title="Update your email" copy="Enter the email address you’d like to use for your account." back={back}><form className="auth-form" onSubmit={submit}><AuthField label="Email address" value={email} onChange={setEmail} placeholder="Enter your email address" error={emailError} />{formError && (emailUpdated ? <div className="auth-inline-success"><Check /> {formError}</div> : <AuthError text={formError} />)}<button className="auth-primary" disabled={loading} type="submit">{loading ? <><RefreshCw className="animate-spin" /> Updating...</> : <>Update Email <ArrowRight /></>}</button></form></AuthShell>;
}

export default function Auth() {
  const [location, setLocation] = useLocation();
  const [email, setEmail] = useState("");
  const [name, setName] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [acceptedTerms, setAcceptedTerms] = useState(false);
  const [remember, setRemember] = useState(true);
  const [twoStepChallengeToken, setTwoStepChallengeToken] = useState("");
  const [twoStepCode, setTwoStepCode] = useState("");
  const [twoStepRecoveryCode, setTwoStepRecoveryCode] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirm, setShowConfirm] = useState(false);
  const [loading, setLoading] = useState(false);
  const [formError, setFormError] = useState("");
  const [emailError, setEmailError] = useState("");
  const [nameError, setNameError] = useState("");
  const [passwordError, setPasswordError] = useState("");
  const [confirmError, setConfirmError] = useState("");
  const [forgotSent, setForgotSent] = useState(false);
  const [resendSeconds, setResendSeconds] = useState(0);
  const [emailUpdated, setEmailUpdated] = useState(false);
  const [verified, setVerified] = useState(false);
  const [manualToken, setManualToken] = useState("");
  const query = new URLSearchParams(window.location.search);
  const route = location.split("?")[0].replace("/auth/", "") || "login";
  const returnPath = getSafeReturnPath(window.location.search);
  const go = (next: string) => { const [nextRoute, nextQuery = ""] = next.split("?"); const params = Object.fromEntries(new URLSearchParams(nextQuery)); setFormError(""); setEmailError(""); setNameError(""); setPasswordError(""); setConfirmError(""); setLocation(withAuthReturn(nextRoute, returnPath, params)); };
  const beginSession = () => { setLocation(returnPath); };
  const socialContinue = () => setFormError("Google sign-in is not available yet. Use your FerixRG email and password to continue.");
  const resend = async () => { const targetEmail = query.get("email") ?? email; if (!emailIsValid(targetEmail)) { setFormError("Enter a valid email address before requesting another verification link."); return; } setLoading(true); setFormError(""); try { const result = await resendVerificationEmail(targetEmail); if (result.delivery && result.delivery !== "sent") { setFormError("Email delivery is not configured in this environment yet. Your account remains protected and can be verified after deployment email settings are added."); return; } setResendSeconds(45); const timer = window.setInterval(() => setResendSeconds(current => { if (current <= 1) { window.clearInterval(timer); return 0; } return current - 1; }), 1000); } catch (error) { setFormError(error instanceof LocalAccountApiError ? error.message : "We couldn’t request another verification email. Please try again."); } finally { setLoading(false); } };

  const submitLogin = async (event: FormEvent) => { event.preventDefault(); setFormError(""); setEmailError(""); setPasswordError(""); if (!emailIsValid(email)) return setEmailError("Please enter a valid email address."); if (!password) return setPasswordError("Enter your password to continue."); setLoading(true); try { const result = await loginLocalAccount({ email, password, remember }); if (result.code === "TWO_STEP_REQUIRED" && result.challengeToken) { setTwoStepChallengeToken(result.challengeToken); setTwoStepCode(""); setTwoStepRecoveryCode(""); return; } beginSession(); } catch (error) { const message = error instanceof LocalAccountApiError && error.code === "VERIFICATION_REQUIRED" ? "Your email address is not verified yet. Open the verification email or request a new verification link." : error instanceof LocalAccountApiError && error.code === "INVALID_CREDENTIALS" ? "Incorrect email or password. Check your details and try again, or use Forgot password." : error instanceof LocalAccountApiError ? error.message : "The account service could not respond. Please try again in a moment."; setFormError(message); } finally { setLoading(false); } };
  const submitTwoStep = async (event: FormEvent) => { event.preventDefault(); setFormError(""); const code = twoStepCode.trim(); const recoveryCode = twoStepRecoveryCode.trim(); if (!code && !recoveryCode) return setFormError("Enter the six-digit code from your authenticator app or a recovery code."); setLoading(true); try { await verifyTwoStepLocalAccount({ challengeToken: twoStepChallengeToken, ...(code ? { code } : { recoveryCode }) }); beginSession(); } catch (error) { setFormError(error instanceof LocalAccountApiError ? error.message : "We couldn’t verify that code. Check it and try again."); } finally { setLoading(false); } };
  const submitRegister = async (event: FormEvent) => { event.preventDefault(); setNameError(""); setEmailError(""); setPasswordError(""); setConfirmError(""); setFormError(""); if (!name.trim()) return setNameError("Please enter your name."); if (!emailIsValid(email)) return setEmailError("Please enter a valid email address."); if (!passwordIsStrong(password)) return setPasswordError("Your password doesn’t meet the requirements."); if (password !== confirmPassword) return setConfirmError("Passwords don’t match."); if (!acceptedTerms) return setFormError("Please accept the Terms of Service and Privacy Policy to continue."); setLoading(true); try { const result = await registerLocalAccount({ name: name.trim(), email, password }); go(`verify-email?email=${encodeURIComponent(email)}${result.delivery && result.delivery !== "sent" ? `&delivery=${encodeURIComponent(result.delivery)}` : ""}`); } catch (error) { setFormError(error instanceof LocalAccountApiError ? error.message : "We couldn’t connect to the server. Check your internet connection and try again."); } finally { setLoading(false); } };
  const submitForgot = async (event: FormEvent) => { event.preventDefault(); setEmailError(""); setFormError(""); if (!emailIsValid(email)) return setEmailError("Please enter a valid email address."); setLoading(true); try { const result = await requestPasswordReset(email); if (result.delivery && result.delivery !== "sent") { setFormError("Password-reset email delivery is not configured in this environment yet. No reset link was sent."); return; } setForgotSent(true); } catch (error) { setFormError(error instanceof LocalAccountApiError ? error.message : "We couldn’t request a reset link. Please try again."); } finally { setLoading(false); } };
  const submitReset = async (event: FormEvent) => { event.preventDefault(); setPasswordError(""); setConfirmError(""); setFormError(""); if (!passwordIsStrong(password)) return setPasswordError("Your password doesn’t meet the requirements."); if (password !== confirmPassword) return setConfirmError("Passwords don’t match."); const token = query.get("token"); if (!token) return setFormError("This password reset link is invalid or incomplete."); setLoading(true); try { await resetLocalPassword({ token, password }); go("reset-success"); } catch (error) { setFormError(error instanceof LocalAccountApiError ? error.message : "We couldn’t reset your password. Please request another link."); } finally { setLoading(false); } };


  const verificationAttempted = useRef<string | null>(null);
  const verificationToken = query.get("token");
  const completeVerification = async () => { const token = query.get("token"); if (!token) { setFormError("Open the verification link sent to your email to activate your account."); return; } setLoading(true); setFormError(""); try { await verifyLocalAccount(token); setVerified(true); } catch (error) { const message = error instanceof LocalAccountApiError && error.code === "VERIFICATION_LINK_INVALID" ? "This verification link is invalid, expired, or has already been used. Request a new verification email and open the newest link." : error instanceof LocalAccountApiError ? error.message : "We couldn’t verify that link because the server did not respond correctly. Please request a new verification email."; setFormError(message); } finally { setLoading(false); } };
  useEffect(() => {
    if (route !== "verify-email" || !verificationToken || verificationAttempted.current === verificationToken) return;
    verificationAttempted.current = verificationToken;
    void completeVerification();
  }, [route, verificationToken]);
  const completeEmailChange = async () => { const token = query.get("token"); if (!token) { setFormError("This email confirmation link is invalid or incomplete."); return; } setLoading(true); setFormError(""); try { await confirmAccountEmailChange(token); setEmailUpdated(true); } catch (error) { setFormError(error instanceof LocalAccountApiError ? error.message : "We couldn’t confirm that email address. Please request another change from your profile."); } finally { setLoading(false); } };

  if (route === "register") return <AuthShell title="Create your account" copy="Start analyzing, improving and redesigning your storefront with powerful e-commerce tools."><form className="auth-form" onSubmit={submitRegister}><AuthField label="Full name" value={name} onChange={setName} placeholder="Enter your full name" error={nameError} /><AuthField label="Email address" value={email} onChange={setEmail} placeholder="Enter your email address" error={emailError} /><AuthField label="Password" value={password} onChange={setPassword} placeholder="Create a password" type={showPassword ? "text" : "password"} error={passwordError} trailing={<button type="button" aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff /> : <Eye />}</button>} /><div className="auth-password-rules">{passwordRules.map((rule, index) => <span className={password && [password.length >= 8, /[A-Z]/.test(password), /[a-z]/.test(password), /\d/.test(password), /[^A-Za-z0-9]/.test(password)][index] ? "met" : ""} key={rule}><Check /> {rule}</span>)}</div><AuthField label="Confirm password" value={confirmPassword} onChange={setConfirmPassword} placeholder="Re-enter your password" type={showConfirm ? "text" : "password"} error={confirmError} trailing={<button type="button" aria-label={showConfirm ? "Hide confirmation password" : "Show confirmation password"} onClick={() => setShowConfirm(!showConfirm)}>{showConfirm ? <EyeOff /> : <Eye />}</button>} /><label className="auth-checkbox"><input type="checkbox" checked={acceptedTerms} onChange={event => setAcceptedTerms(event.target.checked)} /><span>I agree to the <button type="button">Terms of Service</button> and <button type="button">Privacy Policy</button>.</span></label>{formError && <AuthError text={formError} actions={email.includes("used") ? [{ label: "Sign In", onClick: () => go("login") }, { label: "Forgot Password", onClick: () => go("forgot-password") }] : undefined} />}<button className="auth-primary" disabled={loading} type="submit">{loading ? <><RefreshCw className="animate-spin" /> Creating account...</> : <>Create Account <ArrowRight /></>}</button><Divider /><GoogleButton onClick={socialContinue} /><p className="auth-switch">Already have an account? <button type="button" onClick={() => go("login")}>Sign In</button></p></form></AuthShell>;
  if (route === "forgot-password") return forgotSent ? <StatusScreen icon={<Mail />} title="Check your email" copy="If the email address is associated with an account, you’ll receive a password reset link shortly." primary={{ label: "Open Email", onClick: () => openMailApp(email) }} secondary={{ label: "Back to Sign In", onClick: () => go("login") }} /> : <AuthShell title="Reset your password" copy="Enter the email address associated with your account and we’ll send you instructions to reset your password." back={() => go("login")}><form className="auth-form" onSubmit={submitForgot}><AuthField label="Email address" value={email} onChange={setEmail} placeholder="Enter your email address" error={emailError} />{formError && <AuthError text={formError} />}<button className="auth-primary" disabled={loading} type="submit">{loading ? <><RefreshCw className="animate-spin" /> Sending link...</> : <>Send Reset Link <ArrowRight /></>}</button><p className="auth-switch"><button type="button" onClick={() => go("login")}>Back to Sign In</button></p></form></AuthShell>;
  if (route === "reset-password") return <AuthShell title="Create a new password" copy="Choose a strong password for your account." back={() => go("login")}><form className="auth-form" onSubmit={submitReset}><AuthField label="New password" value={password} onChange={setPassword} placeholder="Enter new password" type={showPassword ? "text" : "password"} error={passwordError} trailing={<button type="button" aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff /> : <Eye />}</button>} /><div className="auth-password-rules">{passwordRules.map(rule => <span key={rule}><Check /> {rule}</span>)}</div><AuthField label="Confirm new password" value={confirmPassword} onChange={setConfirmPassword} placeholder="Re-enter new password" type={showConfirm ? "text" : "password"} error={confirmError} trailing={<button type="button" aria-label={showConfirm ? "Hide confirmation password" : "Show password"} onClick={() => setShowConfirm(!showConfirm)}>{showConfirm ? <EyeOff /> : <Eye />}</button>} />{formError && <AuthError text={formError} />}<button className="auth-primary" disabled={loading} type="submit">{loading ? <><RefreshCw className="animate-spin" /> Resetting password...</> : <>Reset Password <ArrowRight /></>}</button></form></AuthShell>;
  if (route === "reset-success") return <StatusScreen icon={<CircleCheck />} title="Password updated" copy="Your password has been changed successfully. You can now sign in with your new password." primary={{ label: "Sign In", onClick: () => go("login") }} />;
  if (route === "reset-expired") return <StatusScreen icon={<Clock3 />} title="Reset link expired" copy="This password reset link is no longer valid. Request a new one to reset your password." primary={{ label: "Request New Reset Link", onClick: () => go("forgot-password") }} secondary={{ label: "Back to Sign In", onClick: () => go("login") }} />;
  if (route === "reset-invalid") return <StatusScreen icon={<TriangleAlert />} title="Invalid reset link" copy="This password reset link is invalid or has already been used." primary={{ label: "Request New Reset Link", onClick: () => go("forgot-password") }} />;
  if (route === "change-email") return <EmailChangeScreen initialEmail={query.get("email") ?? email} back={() => go("verify-email")} />;
  if (route === "confirm-email-change") return emailUpdated ? <StatusScreen icon={<CircleCheck />} title="Email updated" copy="Your new email address is verified and ready to use for your FerixRG account." primary={{ label: "Continue to sign in", onClick: () => go("login") }} /> : <AuthShell title="Confirm your new email" copy="Use this confirmation to finish updating the email address on your FerixRG account."><div className="auth-status"><div className="auth-status-icon waiting"><Mail /></div>{formError && <AuthError text={formError} />}<button className="auth-primary" disabled={loading} onClick={completeEmailChange}>{loading ? <><RefreshCw className="animate-spin" /> Confirming...</> : <>Confirm Email Address <ArrowRight /></>}</button><button className="auth-text-action" onClick={() => go("login")}>Back to Sign In</button></div></AuthShell>;
  if (route === "verify-email") { const targetEmail = (query.get("email") ?? email) || "user@example.com"; const deliveryBlocked = query.get("delivery") && query.get("delivery") !== "sent"; const verifyManualToken = async () => { if (!manualToken.trim()) { setFormError("Please enter the verification token from your email."); return; } setLoading(true); setFormError(""); try { await verifyLocalAccount(manualToken.trim()); setVerified(true); } catch (error) { const message = error instanceof LocalAccountApiError && error.code === "VERIFICATION_LINK_INVALID" ? "This verification token is invalid, expired, or has already been used. Request a new verification email." : error instanceof LocalAccountApiError ? error.message : "We couldn’t verify that token. Please check and try again."; setFormError(message); } finally { setLoading(false); } }; return verified ? <StatusScreen icon={<CircleCheck />} title="Email verified" copy="Your account has been verified successfully. You can now sign in and access your workspace." primary={{ label: "Continue to sign in", onClick: () => setLocation("/auth/login") }} /> : <AuthShell title="Verify your email" copy={`We’ve sent a verification link to ${targetEmail}. Open the email and click the verification link to activate your account.`}><div className="auth-status"><div className="auth-status-icon waiting"><Mail /></div>{loading ? <div className="auth-waiting"><i /><span>Verifying your email link...</span></div> : <div className="auth-waiting"><i /><span>Waiting for verification...</span></div>}{deliveryBlocked && <AuthError text="Email delivery is not configured in this environment yet. Your account has not received a verification link." />}{formError && <AuthError text={formError} />}<button className="auth-primary" disabled={loading} onClick={completeVerification}>{loading ? <><RefreshCw className="animate-spin" /> Verifying...</> : <>I’ve verified my email <ArrowRight /></>}</button><button className="auth-secondary" onClick={() => openMailApp(targetEmail)}>Open Email</button><div className="auth-divider">or enter token manually</div><AuthField label="Verification token" value={manualToken} onChange={setManualToken} placeholder="Paste token from email" type="text" error={formError?.includes("token") ? formError : undefined} /><button className="auth-primary" disabled={loading || !manualToken.trim()} onClick={verifyManualToken}>{loading ? <><RefreshCw className="animate-spin" /> Verifying...</> : <>Verify Token <ArrowRight /></>}</button><button className="auth-text-action" disabled={resendSeconds > 0 || loading} onClick={resend}>{resendSeconds > 0 ? `Resend in 00:${String(resendSeconds).padStart(2, "0")}` : "Resend Verification Email"}</button><button className="auth-text-action" onClick={() => go("change-email")}>Change Email Address</button></div></AuthShell>; }
  if (route === "verification-success") return <StatusScreen icon={<CircleCheck />} title="Email verified" copy="Your account has been verified successfully." primary={{ label: "Continue", onClick: () => go("onboarding") }} />;
  if (route === "verification-expired") return <StatusScreen icon={<Clock3 />} title="Verification link expired" copy="This verification link is no longer valid. Request a new verification email to continue." primary={{ label: "Send New Verification Link", onClick: () => go("verify-email") }} />;
  if (route === "verification-invalid") return <StatusScreen icon={<TriangleAlert />} title="Invalid verification link" copy="This verification link is invalid or has already been used." primary={{ label: "Request New Verification Email", onClick: () => go("verify-email") }} />;
  if (route === "onboarding") return <AuthShell title="Your workspace is ready" copy="A brief orientation before you start improving your storefront."><div className="auth-onboarding"><span><Check /> Store intelligence is ready</span><span><Check /> Your tools are organized by task</span><span><Check /> You can connect a store whenever you need private context</span><button className="auth-primary" onClick={beginSession}>Go to dashboard <ArrowRight /></button><button className="auth-text-action" onClick={beginSession}>Skip for now</button></div></AuthShell>;
  if (route === "login" && twoStepChallengeToken) return <AuthShell title="Verify your sign-in" copy="Enter the code from your authenticator app, or use one of your recovery codes."><form className="auth-form" onSubmit={submitTwoStep}><AuthField label="Authenticator code" value={twoStepCode} onChange={value => setTwoStepCode(value.replace(/\D/g, "").slice(0, 6))} placeholder="Enter 6-digit code" type="text" /><AuthField label="Recovery code (optional)" value={twoStepRecoveryCode} onChange={setTwoStepRecoveryCode} placeholder="Use a recovery code instead" type="text" />{formError && <AuthError text={formError} />}<button className="auth-primary" disabled={loading} type="submit">{loading ? <><RefreshCw className="animate-spin" /> Verifying...</> : <>Verify and Sign In <ArrowRight /></>}</button><button type="button" className="auth-text-action" onClick={() => { setTwoStepChallengeToken(""); setTwoStepCode(""); setTwoStepRecoveryCode(""); }}>Use a different sign-in</button></form></AuthShell>;
  const isSessionExpired = query.get("reason") === "session";
  return <AuthShell title="Welcome back" copy="Sign in to continue managing, analyzing and improving your storefronts."><form className="auth-form" onSubmit={submitLogin}><AuthField label="Email address" value={email} onChange={setEmail} placeholder="Enter your email address" error={emailError} /><AuthField label="Password" value={password} onChange={setPassword} placeholder="Enter your password" type={showPassword ? "text" : "password"} error={passwordError} trailing={<button type="button" aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff /> : <Eye />}</button>} /><div className="auth-options"><label className="auth-checkbox"><input type="checkbox" checked={remember} onChange={event => setRemember(event.target.checked)} /><span>Remember me</span></label><button type="button" onClick={() => go("forgot-password")}>Forgot password?</button></div>{formError && <AuthError text={formError} actions={formError.includes("verified") ? [{ label: "Resend verification email", onClick: () => go("verify-email") }] : undefined} />}<button className="auth-primary" disabled={loading} type="submit">{loading ? <><RefreshCw className="animate-spin" /> Signing in...</> : <>Sign In <ArrowRight /></>}</button><Divider /><GoogleButton onClick={socialContinue} /><p className="auth-switch">Don’t have an account? <button type="button" onClick={() => go("register")}>Create an account</button></p></form>{isSessionExpired && <div className="auth-session-layer" role="dialog" aria-modal="true" aria-labelledby="auth-session-expired-title"><div><ShieldCheck /><h2 id="auth-session-expired-title">Your session has expired</h2><p>For your security, you’ve been signed out. Please sign in again to continue.</p><button className="auth-primary" onClick={() => setLocation("/auth/login")}>Sign In <ArrowRight /></button></div></div>}</AuthShell>;
}

function AuthError({ text, actions }: { text: string; actions?: Array<{ label: string; onClick: () => void }> }) { return <div className="auth-error" role="alert"><TriangleAlert /><div><b>{text}</b>{actions && <span>{actions.map(action => <button type="button" onClick={action.onClick} key={action.label}>{action.label}</button>)}</span>}</div></div>; }
