import React from "react";
import { ArrowRight, Check, Mail, ShieldCheck, Sparkles } from "lucide-react";
import { useLocation } from "wouter";
import { landingHealthMetrics, landingIssueList, landingOutcomes, landingWorkflow, publicPageCopy, supportedPlatforms } from "@/lib/landingContent";
import { afterAsset, beforeAsset, heroAsset, issueCardVisuals, mobileAsset, PrimaryButton, PublicPage, VisualCarousel } from "@/components/PublicSite";

function PageHero({ page }: { page: keyof typeof publicPageCopy }) {
  const [, navigate] = useLocation();
  const copy = publicPageCopy[page];
  return <section className="landing-section public-page-hero"><div><div className="landing-eyebrow">{copy.eyebrow}</div><h1>{copy.title}</h1><p>{copy.copy}</p><div className="hero-actions"><PrimaryButton onClick={() => navigate("/app")}>Analyze Your Store</PrimaryButton><button type="button" className="landing-secondary" onClick={() => navigate("/auth/register")}>Create Free Account</button></div></div><img src={heroAsset} alt="FerixRG storefront intelligence workspace" /></section>;
}

function OutcomeStrip() {
  return <section className="outcome-strip">{landingOutcomes.map(outcome => <div className="outcome" key={outcome.label}><i>{outcome.icon}</i><p><b>{outcome.value}<small>{outcome.suffix}</small></b><span>{outcome.label}</span></p></div>)}</section>;
}

export function FeaturesPage() {
  const [, navigate] = useLocation();
  return <PublicPage><PageHero page="features" /><OutcomeStrip /><section className="landing-section finding-section"><div className="finding-main"><div className="landing-eyebrow">WHAT WE FIND</div><h2>Your store may have problems you can’t see.</h2><VisualCarousel className="finding-carousel" label="Store analysis visual carousel" /><div className="issue-cards">{issueCardVisuals.map(item => <article key={item.title}><img src={item.src} alt={item.alt} /><div><b><i />{item.title}</b><p>{item.copy}</p></div></article>)}</div></div><aside className="change-story"><img src={heroAsset} alt="Storefront findings overview" /><ul>{landingIssueList.map(item => <li key={item}>{item}</li>)}</ul><button type="button" onClick={() => navigate("/app")}>View full analysis <ArrowRight size={13} /></button></aside></section><section className="health-report"><header><b>Your Store Health Report</b><button type="button" onClick={() => navigate("/app")}>Open workspace <ArrowRight size={13} /></button></header><img src={heroAsset} alt="Store health report evidence" /><div>{landingHealthMetrics.map(metric => <article key={metric.name}><span>{metric.name}</span><b>{metric.value}</b><i className={metric.tone} /></article>)}</div></section></PublicPage>;
}

export function SolutionsPage() {
  const [, navigate] = useLocation();
  const solutionCards = [["Store owners", "See the highest-impact opportunities before spending time or budget on changes.", "Health reports, evidence, and prioritized next actions."], ["Design teams", "Move from visual review to a clear proposal without losing the original storefront context.", "Responsive evidence, redesign alternatives, and reviewable drafts."], ["Agencies", "Give every client a repeatable intelligence workflow and a more defensible recommendation.", "Scoped analysis, saved versions, and export-ready results."], ["Developers", "Receive implementation context only after the recommendation has been reviewed and validated.", "Acceptance criteria, evidence boundaries, and responsible handoff." ]];
  return <PublicPage><PageHero page="solutions" /><section className="landing-section public-card-grid">{solutionCards.map(([title, copy, result]) => <article className="approved-panel" key={title}><span className="landing-eyebrow">{title}</span><h2>{copy}</h2><p>{result}</p><button type="button" className="landing-secondary" onClick={() => navigate("/app")}>Explore workspace <ArrowRight size={13} /></button></article>)}</section><section className="ai-band"><div><div className="landing-eyebrow">ASK FERIXRG AI</div><h2>Don’t just find the problem.<br />Fix it.</h2><p>FerixRG AI turns insight into action—instantly.</p></div><div className="prompt-grid">{[["Improve product page conversion", "product-composer"], ["Speed up my store", "performance-evidence"], ["Redesign with a modern look", "responsive-redesign"], ["Improve mobile checkout", "checkout-friction"]].map(([prompt, toolId]) => <button type="button" onClick={() => navigate(`/auth/register?returnTo=${encodeURIComponent(`/app/tools?tool=${toolId}`)}`)} key={prompt}>{prompt} <ArrowRight size={12} /></button>)}</div></section></PublicPage>;
}

export function HowItWorksPage() {
  const [, navigate] = useLocation();
  return <PublicPage><PageHero page="howItWorks" /><section className="landing-section workflow-section"><div className="landing-eyebrow">PROVEN PROCESS</div><h2>From insight to impact.</h2><div className="workflow-cards">{landingWorkflow.map(([number, title, copy]) => <article key={number}><b>{number}</b><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section><section className="landing-section evidence-section"><div className="landing-eyebrow">EVIDENCE READY</div><h2>Every improvement has proof.</h2><VisualCarousel className="evidence-carousel" label="Evidence and redesign visual carousel" /><div className="evidence-cards"><article><b>01 &nbsp; Responsive test</b><img src={mobileAsset} alt="Allbirds responsive mobile storefront test" /><small>Three mobile storefront views compared.</small></article><article><b>02 &nbsp; Storefront redesign alternative</b><img src={afterAsset} alt="Supplied Shopify storefront redesign comparison" /><small>Compare directions before publishing.</small></article><article><b>03 &nbsp; Report-ready improvements</b><img src="/landing/portfolio/portfolio-before-after-jewelry.jpg" alt="Jewelry storefront before and after improvement report" /><small>Before-and-after evidence ready for review.</small></article></div></section><section className="redesign-compare"><article className="before"><span>Before</span><b>72 <small>/100</small></b><img src={beforeAsset} alt="Afrogem storefront before redesign" /></article><article className="after"><span>After</span><b>94 <small>/100</small></b><img src={afterAsset} alt="Supplied Shopify storefront after redesign" /></article></section><section className="landing-cta"><h2>Ready to see your own evidence?</h2><PrimaryButton onClick={() => navigate("/app")}>Analyze My Store</PrimaryButton></section></PublicPage>;
}

export function PlatformsPage() {
  return <PublicPage><PageHero page="platforms" /><section className="platform-band"><header><span>SUPPORTED PLATFORMS</span><ArrowRight size={18} /></header><div className="platform-track"><div>{[...supportedPlatforms, ...supportedPlatforms].map((platform, index) => <span className={`platform-logo ${platform.tone}`} key={`${platform.name}-${index}`}><b>{platform.mark}</b>{platform.name}</span>)}</div></div></section><p className="platform-note">◉ Analyze any public store URL instantly, or connect your store for deeper insights, monitoring, and publishing.</p><OutcomeStrip /><section className="landing-section public-card-grid"><article className="approved-panel"><ShieldCheck /><h2>Public URL analysis</h2><p>Analyze pages your visitors can see without requiring a store connection.</p></article><article className="approved-panel"><Check /><h2>Connected store context</h2><p>Use granted provider context for deeper workflows where the adapter and permissions are configured.</p></article><article className="approved-panel"><Sparkles /><h2>Responsible publishing</h2><p>Review evidence and capability boundaries before any store-side release action.</p></article></section></PublicPage>;
}

export function ResourcesPage() {
  return <PublicPage><PageHero page="resources" /><section className="landing-section evidence-section"><div className="landing-eyebrow">EVIDENCE READY</div><h2>Every improvement has proof.</h2><VisualCarousel className="evidence-carousel" label="Resource visual carousel" /><div className="evidence-cards"><article><b>Reports</b><img src={heroAsset} alt="Store health report resource" /><small>Readable evidence for decisions and handoff.</small></article><article><b>Before and after</b><img src={beforeAsset} alt="Afrogem before and after resource" /><small>Compare the starting point with the direction you want.</small></article><article><b>Mobile guidance</b><img src={mobileAsset} alt="Mobile storefront resource" /><small>Keep responsive behavior visible throughout review.</small></article></div></section><section className="landing-section public-card-grid"><article className="approved-panel"><h2>What’s New</h2><p>Review product changes without interrupting active storefront work.</p></article><article className="approved-panel"><h2>Help and guidance</h2><p>Understand source boundaries, evidence, connected stores, and workspace actions.</p></article><article className="approved-panel"><h2>Report a problem</h2><p>Send context-rich feedback from the workspace when something does not behave as expected.</p></article></section></PublicPage>;
}

export function PricingPage() {
  const [, navigate] = useLocation();
  const plans: Array<[string, string, string[]]> = [["Explore", "For a first storefront assessment", ["Public URL analysis", "Core health findings", "Evidence-led next actions"]], ["Improve", "For teams actively redesigning a store", ["Everything in Explore", "AI proposals and workspace drafts", "Responsive and conversion workflows"]], ["Scale", "For agencies and connected operations", ["Everything in Improve", "Connected-store context", "Team review and release readiness"]]];
  return <PublicPage><PageHero page="pricing" /><section className="landing-section public-card-grid pricing-grid">{plans.map(([name, copy, features]) => <article className="approved-panel" key={name}><div className="landing-eyebrow">{name}</div><h2>{copy}</h2><div className="tool-workflow-package-list">{features.map(feature => <span key={feature}>✓ {feature}</span>)}</div><PrimaryButton onClick={() => navigate("/auth/register")}>Get Started</PrimaryButton></article>)}</section><section className="landing-cta"><h2>Start with the access you already have.</h2><PrimaryButton onClick={() => navigate("/app")}>Analyze My Store</PrimaryButton></section></PublicPage>;
}

export function AboutPage() {
  return <PublicPage><PageHero page="about" /><section className="landing-section public-card-grid"><article className="approved-panel"><Sparkles /><h2>Evidence before automation</h2><p>FerixRG is designed to separate what was observed from what is recommended, so teams can review a change before acting on it.</p></article><article className="approved-panel"><ShieldCheck /><h2>Boundaries that stay visible</h2><p>Public analysis, connected-store permissions, provider readiness, and publishing capability are represented honestly.</p></article><article className="approved-panel"><Check /><h2>Work that remains reviewable</h2><p>Reports, drafts, versions, validation, and handoff context make the work understandable after the initial run.</p></article></section></PublicPage>;
}

export function ContactPage() {
  return <PublicPage><PageHero page="contact" /><section className="landing-section contact-panel"><div className="approved-panel"><Mail /><h2>Tell us what you need to improve.</h2><p>Use the workspace support flow for account-specific help, or send a general product question by email.</p><a className="landing-primary" href="mailto:support@ferixas.com">Contact FerixRG <ArrowRight size={14} /></a></div></section></PublicPage>;
}
