import { ArrowLeft, Check, ChevronRight, FileBarChart, Save, ShieldCheck } from "lucide-react";
import React, { useState } from "react";
import "./moreActionPanel.css";

type Field = { label: string; value: string; type?: "text" | "email" | "select"; options?: string[] };
type Detail = {
  eyebrow: string;
  title: string;
  copy: string;
  metrics: [string, string][];
  rows?: string[];
  fields?: Field[];
  toggles?: { label: string; copy: string; enabled?: boolean }[];
  choices?: string[];
  primary: string;
  completion: string;
  destructive?: boolean;
};

export const moreActionDetails: Record<string, Detail> = {
  "billing:Subscription": { eyebrow: "Plan and usage", title: "Subscription", copy: "Review the workspace plan and choose the amount of FerixRG capacity the team needs.", metrics: [["Free", "Current plan"], ["Sep 1", "Next renewal"]], choices: ["Free", "Pro", "Studio"], rows: ["1 workspace included", "2 of 3 team seats used", "20 monthly analyses"], primary: "Keep Free plan", completion: "Your selected plan is saved for this preview." },
  "billing:Usage limits": { eyebrow: "Plan and usage", title: "Usage limits", copy: "See what the workspace has used and decide when FerixRG should warn the team before a limit is reached.", metrics: [["12 / 20", "Store analyses"], ["8", "Analyses remaining"]], fields: [{ label: "Usage alert threshold", value: "80%", type: "select", options: ["50%", "80%", "90%"] }], rows: ["1 of 2 connected stores", "2 of 3 team seats", "14 of 30 saved draft versions"], primary: "Save usage alert", completion: "Usage alert preference saved." },
  "billing:AI credits": { eyebrow: "Plan and usage", title: "AI credits", copy: "Keep AI-assisted work visible with a simple breakdown of the current credit allowance.", metrics: [["240", "Credits remaining"], ["760", "Credits used"]], rows: ["14 design proposals", "51 structured suggestions", "6 reference analyses"], fields: [{ label: "Credit alert threshold", value: "100 credits", type: "select", options: ["50 credits", "100 credits", "200 credits"] }], primary: "Save credit alert", completion: "AI credit alert saved." },
  "billing:Billing history": { eyebrow: "Plan and usage", title: "Billing history", copy: "Review the workspace’s simulated plan record and download an available receipt.", metrics: [["3", "Receipts available"], ["$0", "Current balance"]], rows: ["Aug 2026 · Free plan receipt", "Jul 2026 · Free plan receipt", "Jun 2026 · Free plan receipt"], primary: "Download latest receipt", completion: "The latest receipt is ready for download in this preview." },
  "profile:Personal details": { eyebrow: "Personal account", title: "Personal details", copy: "Update your own display information without changing shared workspace or store settings.", metrics: [["Owner", "Workspace role"], ["UTC+1", "Time zone"]], fields: [{ label: "Full name", value: "Maya Turner" }, { label: "Role or title", value: "Store operations" }], primary: "Save personal details", completion: "Personal details saved in this preview." },
  "profile:Email address": { eyebrow: "Personal account", title: "Email address", copy: "Use a verified email address to keep account notifications and sign-in recovery available.", metrics: [["Verified", "Current email"], ["1", "Recovery method"]], fields: [{ label: "New email address", value: "maya@atelierforma.com", type: "email" }], primary: "Send verification", completion: "A verification message has been prepared for the new address." },
  "profile:Password & security": { eyebrow: "Personal account", title: "Password & security", copy: "Review the main protection controls for your personal FerixRG account.", metrics: [["28 days", "Since password update"], ["Enabled", "Recovery method"]], toggles: [{ label: "Two-step verification", copy: "Ask for an additional code after password sign-in.", enabled: true }, { label: "Security alerts", copy: "Receive an alert when a new sign-in is detected.", enabled: true }], primary: "Send password reset link", completion: "A password reset link has been prepared for this preview." },
  "profile:Connected sessions": { eyebrow: "Personal account", title: "Connected sessions", copy: "Review the devices signed into your account and safely remove old browser sessions.", metrics: [["2", "Active sessions"], ["Today", "Last activity"]], rows: ["Chrome on macOS · Current session", "Safari on iPhone · Last active today"], primary: "Sign out other sessions", completion: "Other preview sessions have been signed out." },
  "preferences:Workspace defaults": { eyebrow: "Personal defaults", title: "Workspace defaults", copy: "Set the starting context FerixRG should use when you open your workspace.", metrics: [["Atelier Forma", "Default store"], ["Mobile", "Default viewport"]], fields: [{ label: "Default store", value: "Atelier Forma", type: "select", options: ["Atelier Forma", "Northlight Home", "Modo Supply"] }, { label: "Default preview", value: "Mobile", type: "select", options: ["Desktop", "Tablet", "Mobile"] }], primary: "Save defaults", completion: "Workspace defaults saved for your account." },
  "preferences:Notifications": { eyebrow: "Personal defaults", title: "Notifications", copy: "Choose which work events need your attention without changing what the rest of the team receives.", metrics: [["3", "Active alerts"], ["Email", "Delivery method"]], toggles: [{ label: "Analysis ready", copy: "Alert when a store analysis is complete.", enabled: true }, { label: "Draft review", copy: "Alert when a shared draft needs review.", enabled: true }, { label: "Publishing readiness", copy: "Alert when a supported release is ready.", enabled: true }], primary: "Save notifications", completion: "Notification preferences saved." },
  "preferences:Product updates": { eyebrow: "Personal defaults", title: "Product updates", copy: "Control how you hear about FerixRG releases, product improvements, and optional research.", metrics: [["Monthly", "Release summary"], ["Off", "Research invites"]], toggles: [{ label: "Release notes", copy: "Receive concise product release summaries.", enabled: true }, { label: "Product research", copy: "Receive optional invitations to feedback sessions." }], primary: "Save product updates", completion: "Product update preferences saved." },
  "preferences:Accessibility": { eyebrow: "Personal defaults", title: "Accessibility", copy: "Make the FerixRG workspace easier to use without affecting other team members’ preferences.", metrics: [["Standard", "Text scale"], ["On", "Visible focus"]], toggles: [{ label: "Reduce motion", copy: "Limit non-essential animated transitions." }, { label: "Increase contrast", copy: "Use stronger separation between content surfaces." }, { label: "Visible keyboard focus", copy: "Keep keyboard focus indicators visible.", enabled: true }], primary: "Save accessibility settings", completion: "Accessibility preferences saved." },
  "platform:Integrations": { eyebrow: "Workspace connections", title: "Integrations", copy: "Review the systems currently connected to FerixRG and what each connection can do.", metrics: [["1", "Connected platform"], ["Supported", "Release capability"]], rows: ["Shopify · Atelier Forma · Connected", "URL analysis · Public evidence available", "Developer handoff · Export available"], primary: "Refresh Shopify permissions", completion: "Shopify permissions have been refreshed in this preview." },
  "platform:Developer & API": { eyebrow: "Workspace connections", title: "Developer & API", copy: "Use structured handoff and API access when implementation needs to move beyond the visual editor.", metrics: [["1", "Developer workflow"], ["JSON", "Handoff format"]], rows: ["Theme patch proposals", "Structured issue evidence", "Developer handoff packages"], primary: "Prepare developer handoff", completion: "A developer handoff package is ready in this preview." },
  "platform:API keys": { eyebrow: "Workspace connections", title: "API keys", copy: "Manage simulated API access keys for controlled integration and developer workflows.", metrics: [["1", "Active preview key"], ["Restricted", "Current scope"]], rows: ["ferix_preview_••••81C2 · Created today", "Scope: read analysis and export handoff"], primary: "Create API key", completion: "A new preview API key has been generated and shown only once." },
  "platform:Request a platform": { eyebrow: "Workspace connections", title: "Request a platform", copy: "Tell the FerixRG team which storefront platform you want to connect next.", metrics: [["5", "Platforms supported"], ["URL", "Fallback available"]], fields: [{ label: "Platform name", value: "" }, { label: "Storefront URL (optional)", value: "", type: "text" }], primary: "Send platform request", completion: "Platform request submitted for review." },
  "resources:Documentation": { eyebrow: "Product guidance", title: "Documentation", copy: "Find the guidance needed to use the selected FerixRG workflow with confidence.", metrics: [["23", "Tools documented"], ["6", "Guides updated"]], rows: ["Choose and run a tool", "Review evidence and reports", "Use the shared editor", "Validate, publish, or export"], primary: "Open tool guide", completion: "The selected documentation guide is open in this preview." },
  "resources:Help Center": { eyebrow: "Product guidance", title: "Help Center", copy: "Browse answers for account, store connection, evidence, editing, and release questions.", metrics: [["5", "Help categories"], ["24 h", "Support guidance"]], rows: ["Getting started", "Store connections", "Tools and evidence", "Editing and versions", "Publishing and exports"], primary: "Open help topic", completion: "The selected help topic is open in this preview." },
  "resources:What’s New": { eyebrow: "Product guidance", title: "What’s New", copy: "Review concise product changes without interrupting active storefront work.", metrics: [["3", "Recent updates"], ["Today", "Last release"]], rows: ["Shared AI and manual editor", "Context-aware release routing", "Team access management"], primary: "Mark updates as read", completion: "Updates marked as read." },
  "resources:About": { eyebrow: "Product guidance", title: "About FerixRG", copy: "FerixRG helps teams understand, improve, validate, and responsibly deliver storefront changes.", metrics: [["23", "Tools"], ["5", "Supported paths"]], rows: ["Storefront intelligence", "Design and content correction", "Optimization and developer handoff"], primary: "View product overview", completion: "Product overview opened in this preview." },
  "resources:Terms": { eyebrow: "Product guidance", title: "Terms", copy: "Review the product terms used for this simulated FerixRG workspace.", metrics: [["Current", "Terms version"], ["Aug 2026", "Last updated"]], rows: ["Account responsibilities", "Store connection boundaries", "Export and publishing responsibilities"], primary: "View full terms", completion: "Full terms view opened in this preview." },
  "resources:Privacy": { eyebrow: "Product guidance", title: "Privacy", copy: "Review how this simulated workspace represents data, connections, and account privacy.", metrics: [["Current", "Privacy version"], ["Aug 2026", "Last updated"]], rows: ["Store connection data", "Public URL analysis", "Account and workspace data"], primary: "View privacy details", completion: "Privacy details opened in this preview." },
  "support:Contact support": { eyebrow: "Help and feedback", title: "Contact support", copy: "Send a support request with the workspace context needed to understand your question.", metrics: [["24 h", "Response guidance"], ["More", "Context attached"]], fields: [{ label: "Subject", value: "" }, { label: "What do you need help with?", value: "" }], primary: "Send support request", completion: "Support request sent with workspace context." },
  "support:Report a problem": { eyebrow: "Help and feedback", title: "Report a problem", copy: "Describe a problem so the FerixRG team can understand the screen and workspace context involved.", metrics: [["More", "Context attached"], ["Private", "Workspace data"]], fields: [{ label: "What happened?", value: "" }, { label: "Expected result", value: "" }], primary: "Send problem report", completion: "Problem report sent with workspace context." },
  "support:Send feedback": { eyebrow: "Help and feedback", title: "Send feedback", copy: "Share product feedback while the relevant workspace context is still clear.", metrics: [["Optional", "Contact reply"], ["More", "Context attached"]], fields: [{ label: "Your feedback", value: "" }], primary: "Send feedback", completion: "Feedback sent to the product team." },
  "support:Feature requests": { eyebrow: "Help and feedback", title: "Feature requests", copy: "Describe the job you want FerixRG to make easier for your storefront workflow.", metrics: [["Open", "Request status"], ["More", "Context attached"]], fields: [{ label: "Feature request", value: "" }, { label: "Why would this help?", value: "" }], primary: "Submit feature request", completion: "Feature request submitted for review." },
};

export function MoreActionPanel({ section, action, onBack }: { section: string; action: string; onBack: () => void }) {
  const detail = moreActionDetails[`${section}:${action}`];
  const [selectedChoice, setSelectedChoice] = useState(detail?.choices?.[0] ?? "");
  const [saved, setSaved] = useState("");
  if (!detail) return null;
  return <section className="more-action-page"><header className="more-action-header"><button className="more-action-back" onClick={onBack}><ArrowLeft /> Back to {section === "billing" ? "Billing & Usage" : section[0].toUpperCase() + section.slice(1)}</button><span className="approved-eyebrow">{detail.eyebrow}</span><h1>{detail.title}</h1><p>{detail.copy}</p></header><section className="more-action-metrics">{detail.metrics.map(([value, label]) => <article key={label}><b>{value}</b><span>{label}</span></article>)}</section><section className="more-action-grid"><article className="approved-panel more-action-main">{detail.choices && <div className="more-action-choice-group"><span className="approved-eyebrow">Available options</span><div>{detail.choices.map(choice => <button className={selectedChoice === choice ? "selected" : ""} onClick={() => setSelectedChoice(choice)} key={choice}><b>{choice}</b><ChevronRight /></button>)}</div></div>}{detail.fields && <div className="more-action-form"><span className="approved-eyebrow">Update details</span>{detail.fields.map(field => <label key={field.label}>{field.label}{field.type === "select" ? <select defaultValue={field.value}>{field.options?.map(option => <option key={option}>{option}</option>)}</select> : <input type={field.type ?? "text"} defaultValue={field.value} placeholder={field.label} />}</label>)}</div>}{detail.toggles && <div className="more-action-toggle-list"><span className="approved-eyebrow">Controls</span>{detail.toggles.map(toggle => <label key={toggle.label}><span><b>{toggle.label}</b><small>{toggle.copy}</small></span><input type="checkbox" defaultChecked={toggle.enabled} /></label>)}</div>}{detail.rows && <div className="more-action-row-list"><span className="approved-eyebrow">Available details</span>{detail.rows.map(row => <button onClick={() => setSaved(`${row} is ready in this preview.`)} key={row}><span>{row}</span><ChevronRight /></button>)}</div>}<button className="approved-primary more-action-primary" onClick={() => setSaved(detail.completion)}>{detail.destructive ? <ShieldCheck /> : <Save />}{detail.primary}</button></article><aside className="approved-panel more-action-side"><FileBarChart /><span className="approved-eyebrow">Workspace context</span><h2>Keep settings separate from storefront work.</h2><p>Changes here apply only to this simulated workspace setting. Store analyses, editor drafts, and release decisions remain unchanged.</p><div><Check /> <span>Safe preview state</span></div></aside></section>{saved && <section className="more-action-notice"><Check /><div><b>Preview updated</b><p>{saved}</p></div><button onClick={() => setSaved("")}>Dismiss</button></section>}</section>;
}
